### ISSUE TITLE
PDO вместо DbSimple

### ISSUE THREAD

**Issue by beautyfree** [livestreet/livestreet#133]
DbSimple тормозит всю работу ls. Гораздо производительней использовать тот же принцип общения с бд но использую методы PDO написанные на Си, чем эмуляция похожего поведения с помощью DbSimple. Поэтому предлагаю найти библиотеки аналогичные DbSimple с использованием PDO или написать схожую обертку малой кровью.

Для саморазвития http://habrahabr.ru/post/137664/

Что касается системных требований ls так и так не поддерживает php меньше 5.1, с которого PDO и появился.

P.S 2 месяца назад <a href="https://github.com/livestreet/livestreet/commit/57217b0e7302a00d1e9d82a4374512c461f4c27f">локализовав область видимости языковых переменных у плагинов</a> произошло небольшое событие в результате которого плагины для версии 5.1 уже несовместимы без исправлений с версией 1.0. Поэтому даже если изменить принцип работы мэпперов в более гибкую сторону используя все возможности PDO мы приобретем только новое, а разработчикам так и так уже придется плагины исправлять)

**Comment by KarelWintersky** [comment]
И чем всё кончилось? DbSimple на mysqli ?
