### ISSUE TITLE
Внешний ключ таблицы админов не имеет префикса в дампе sql при инсталяции лс

### ISSUE THREAD

**Issue by psnet** [livestreet/livestreet#261]
Это не позволит создать две ЛС в одной БД с разными префиксами (для чего они собственно и сделаны), т.к. внешний ключ таблицы админов не имеет префикса:

https://github.com/livestreet/livestreet/blob/master/install/sql.sql#L998

Вместо user_administrator_fk нужно прописать prefix_user_administrator_fk

Не позволит создать две ЛС т.к. выполнение дампа для второй ЛС с другим префиксом вызовет ошибку, причем в стиле ИнноДБ - малоинформативную т.к. ключ user_administrator_fk уже будет существовать.

**Comment by mzhelskiy** [comment]
Таблица удалена из 2.0
