### ISSUE TITLE
Невозможно одновременно оставаться залогиненным в двух разных браузерах

### ISSUE THREAD

**Issue by pisecx** [livestreet/livestreet#328]
Залогинился в одном браузере. Закрыл браузер, открыл - все ок.
Залогинился во втором. Закрыл, открыл - все ок. Зашел в первый браузер - аутентификация слетела.

**Comment by mzhelskiy** [comment]
fix

**Comment by pisecx** [comment]
Закрыто фиксом или просто закрыто? :)

**Comment by mzhelskiy** [comment]
проверить можно на http://alfa.demo.livestreetcms.com/

**Comment by pisecx** [comment]
Отлично, спасибо!
