### ISSUE TITLE
Сделать универсальную функцию для использования раздельного (не монолитного) кеша

### ISSUE THREAD

**Issue by kpoxas** [livestreet/livestreet#336]
В модулях очень много одинакового кода для использования раздельного кеша (например, при доставании топиков, юзеров по списку айди).
Можно вынести данный метод как хелпер, чтобы можно было использовать в своих плагинах.

**Comment by kpoxas** [comment]
А почему тупиковым?

**Comment by mzhelskiy** [comment]
ну именно на LS с ним производительность проседала, возможно такой подход можно применить к другим специфичным проектам

**Comment by kpoxas** [comment]
Может совсем немного, но с монолитным кешем при любом обновлении топика, например, сбрасываются все кеши коллекций топиков, и идет большая нагрузка на бл

**Comment by mzhelskiy** [comment]
Да, по этой причине раздельный кеш и делался, но на практике не оправдал себя + генерил огромное число запросов к кешу

**Comment by kpoxas** [comment]
Мне кажется при большой активности на сайте, монолитный кеш будет все время в инвалидированном состоянии, что полечет постоянные запросы к БД
