### ISSUE TITLE
Не посылать запрос после каждого символа каптчи на сервер

### ISSUE THREAD

**Issue by psnet** [livestreet/livestreet#461]
**Примечательно**, что данный баг появляется сразу после того как авторизация не прошла, т.е. после этого бага:
https://github.com/livestreet/livestreet/issues/460

Сейчас если включена авторизация с каптчей (general.login.captcha), то при каждом вводе символа в поле ввода для каптчи на сервер посылается аякс запрос.

Следует сделать по таймеру эту отправку (ls.timer.run), чтобы не дергать сервер.

**Comment by mzhelskiy** [comment]
fix
