### ISSUE TITLE
Framework: Заменить min-версии js на обычные

### ISSUE THREAD

**Issue by lifecom** [livestreet/livestreet#505]
Т.к. не исключены проблемы при слиянии и сжатии.
По сути имея возможность слияния и сжатия, смысла в min-версиях нет.

По мотивам [топика...](http://livestreet.ru/blog/questions/17272.html#comment275144)

Из наденных здесь **/framework/frontend/framework/js/vendor/**:
* */jquery-1.9.1.min.js*
* */jquery-ui/js/jquery-ui-1.10.2.custom.min.js*
* */jquery.rich-array.min.js*
* */jquery.placeholder.min.js*

**Comment by deniart** [comment]
Тут проблема только заменой либ не решится, надо разбираться с js-минификатором.

**Comment by mzhelskiy** [comment]
https://github.com/livestreet/livestreet-framework/commit/d28ccf961d7ceea8ae737c9fcccff7e2beefc696
осталось заменить min версии на полные

**Comment by Provolod** [comment]
Максим, а почему решил поставить именно JShrink в качестве минификатора для js файлов? Если я правильно понял, то он не делает замену названий переменных. Или я ошибаюсь?

Я сейчас работаю с JSqueeze https://github.com/nicolas-grekas/JSqueeze Минификатор дает довольно неплохой процент сжатия по сравнению с полными версиями файлов. Чем он хуже того, что вы поставили в новую версию?

**Comment by mzhelskiy** [comment]
заменил https://github.com/livestreet/livestreet-framework/commit/45d1b117134f3464f9e0bd626ac5a1893fbbf3ed

**Comment by deniart** [comment]
> осталось заменить min версии на полные

Зачем? Текущий минификатор вызывает теже проблемы что и предыдущий?

**Comment by mzhelskiy** [comment]
проблем пока не видел
суть в дебаге при отключенном минификаторе

**Comment by lifecom** [comment]
По опыту проблемы возможны с последовательностью js-файлов. Вероятно имеет смысл сделать механизм установки приоритета для сжимаемых файлов.
Что касается самих min-файлов, то разные либы имеют по-разному минифицированные файлы: одни переименовывают переменные, другие просто без white space. Думаю, минифицировать уже минифицированное - источник потенциальных проблем, да и нелогично это как-то...

**Comment by lifecom** [comment]
Кстати, проблемы с последовательность в большей степени касаются css
