### ISSUE TITLE
виджеты ЛС как обертки и префиксы css-классов

### ISSUE THREAD

**Issue by kerbylav** [livestreet/livestreet#547]
Раз пошла такая пьянка...

Было бы очень и очень хорошо превратить js-виджеты типа .modal в обертки, из которых уже вызывать какую-то реальную библиотеку. В частности, меня категорически не устраивает вот этот самый .modal с его, как минимум, невозможностью "вложенных" модальных окон. Хотелось бы подключать какую-то стороннюю библиотеку, типа той же, http://arcticlab.ru/arcticmodal/ но так, чтобы не ломать при этом код и шаблоны. И вот виджет-обертка в этом бы сильно помог. Ну и переименовать эти виджеты в тот же .lsModal вместо .modal для совместимости со сторонними библиотеками. Ну и data-триггеры тоже чтобы обзавелись префиксами...

Так же было бы просто супер, если бы CSS-классы ЛС имели бы собственный префикс, да хоть ls-ххх. Сильно бы упростило интеграцию со сторонними CSS-библиотеками и вообще читаемость шаблонов бы повысило на мой взгляд...

**Comment by mzhelskiy** [comment]
Не у всех хелперов добавлен префикс
