### ISSUE TITLE
Добавить возможность выполнения какого-то js-кода после загрузки модального окна через механизм data-modal-url 

### ISSUE THREAD

**Issue by kerbylav** [livestreet/livestreet#562]
Суть в том, чтобы была возможность как-то проинициализировать содержимое модального окна после его загрузки, возможно через хуки или какие-то кастомные евенты для элемента-тоглера.

**Comment by deniart** [comment]
Теперь можно делать так (только для ajax окон):
```
$('.js-modal-toggle-default').on('lsmodaltoggleshow', function( event, data ) { ... });
```
