### ISSUE TITLE
Избавиться от искусственного ограничения добавления топиков в блоги

### ISSUE THREAD

**Issue by kerbylav** [livestreet/livestreet#587]
Видимо это наследство Хабра, но в подавляющем большинстве у обычных пользователей это лишь вызывает недоумение - почему они не могут публиковать в открытые блоги? Объяснять каждый раз, что надо вступить в блог... Какая такая причина этого? 

Тут, скорее, у блога должен быть какой-то признак, что для того, чтобы в него публиковать надо в него вступить, а по-умолчанию пусть все могут публиковать. И то... это как-то должно быть указано явно. Из серии пусть такой блог будет в списке блогов куда можно публиковать, но с какой-нибудь надписью "требуется вступить перед публикацией".

**Comment by psnet** [comment]
Список всех блогов можно держать в селекте при создании топика, поиск из choosen поможет, даже если их будет 70.

А по поводу строки "читатели блога", то её давно пора бы сменить на "авторы блога" т.к. если они написали топик в блог, следовательно вошли в него, то они "авторы".
