### ISSUE TITLE
Может стоит из коробки ввести пользовательские поля для пользователей, а может и блогов?

### ISSUE THREAD

**Issue by kerbylav** [livestreet/livestreet#594]

**Comment by psnet** [comment]
т.е. доп. поля как в топике?

**Comment by kerbylav** [comment]
Да. 

Но тут возникает нюанс, что какие-то поля нужно делать автоматически редактируемыми пользователем из настроек профиля (/settings/profile/), а какие-то - нет.

Хотя таких нюансов может быть много, скажем использование доп. поля в форме регистрации.

В принципе, можно просто ввести несколько типов доп. полей для пользователя. Тип доп. поля пользователя для заполнения в профиле, тип поля для заполнения при регистрации, типа поля для заполнения при регистрации И в профиле... Опять же, у себя я разграничиваю такие поля с помощью префиксов в коде поля... Но это больше смахивает на костыли, все же. 

Поэтому если это как-то и делать, то... Я не смотрел, но может в движке есть возможность "дополнительных полей для дополнительных полей"? :) Чтобы при добавлении дополнительного поля в админке ему можно было какие-то признаки указать в "человеческом" виде...

**Comment by kerbylav** [comment]
Опять же группировка полей... 

Нет, все же это скорее дело для отдельного плагина.
