### ISSUE TITLE
расширение #order для ORM

### ISSUE THREAD

**Issue by kerbylav** [livestreet/livestreet#598]
Ввести какой-нибудь мегазначок для того, чтобы после него оставить поле сортировки "как есть"

Т.е. чтобы можно было бы делать сложные сортировки, типа:

```php
$aFilter=array(
'#join'=>array(
 'inner join prefix_module_stuff s on t.stuff_id=s.id'=>array(),
),
'#order'=>array(
 '#(t.sort+s.sort*10000)'=>'asc'
)
);
```

**Comment by psnet** [comment]
Я, например, не понял: половину результата (10к записей) сортировать, а остальные - оставить как есть?

**Comment by kerbylav** [comment]
Нет. Хмм... Скажем так: поле sort это поле порядка сортировки. Записи из таблицы t... ну скажем принадлежат группам из таблицы s и группы эти, в свою очередь, так же сортируются. Так вот задача одним запросом получить записи из таблицы t, отсортированные по t.sort, но при этом "сгруппированные" по группам из таблицы s в порядке сортировки этих групп, при условии, что t.sort никогда не становится больше 10000.

Но суть не в этом, проблема в том, что сложные условия сортировки нельзя задать.

**Comment by psnet** [comment]
А на языке СКЛ вы представить это можете или вы хотите чтобы это было через пхп уже?

**Comment by kerbylav** [comment]
Я хочу делать это с помощью ORM, а не плодить методы, да еще и заморачиваться с построением собственного запроса по фильтрам.

Чтобы понятней хочется такой результат:

**таблица t:**

id | stuff_id | name | sort
------------ | ------------- | ---- | ----
1 | 1 | A |2
2 | 1 | B |1
3 | 2 | C | 1
4 | 1 | D |3
5 | 2 | E | 3
6 | 2 | F |2

**таблица s:**

id | name | sort
------------ | ------------- | ---- 
1 |  SA | 2
2 |  SB |1

запрос:
```sql
select t.name, s.name, t.sort, s.sort from t inner join s on t.stuff_id=s.id order by (t.sort + s.sort*10000) asc, t.name asc
```

**результат:**

t.name | s.name | t.sort | s.sort
------------ | ------------- | ----  | ---- 
C|SB|1|1
F|SB|2|1
E|SB|3|1
B|SA|1|2
A|SA|2|2
D|SA|3|2

**Comment by kerbylav** [comment]
Пример, вообще-то, не корректный, т.к. тут можно сделать запрос типа 

```sql
select t.name, s.name, t.sort, s.sort from t inner join s on t.stuff_id=s.id order by c.sort asc, t.sort asc, t.name asc
```

Но как я говорил суть в том, что нельзя сложные сортировки делать

**Comment by mzhelskiy** [comment]
Такие тикеты желательно в репо с framework

**Comment by mzhelskiy** [comment]
fix https://github.com/livestreet/livestreet-framework/commit/1e41ee8a25540dfb3ce8749a31f9c05baca21a72
