### ISSUE TITLE
Множественные языковые файлы

### ISSUE THREAD

**Issue by psnet** [livestreet/livestreet#600]
Проблема
---

При разработке больших плагинов текстовок стает очень много, ориентироваться в единственном языковом файле стает затруднительно даже если использовать вложенные массивы.

Предложение
---

Сделать возможным подключение нескольких языковых файлов плагинов одного языка, с возможностью собственного именования и использования **имени** как префикса для получения текстовки:
```php
ru.php
ru.[name].php
```
Пример
---
```php
ru.general.php
ru.cart.php
ru.common.php
```
При этом все они составляют не единое пространство имен, а попадают в массив где *ключ* == **имени** языкового файла,т.е. для примеров выше текстовки будут доступны по ключу:
```
$aLang.plugin.test.general.text
$aLang.plugin.test.cart.submit
$aLang.plugin.test.common.yes
```

**Comment by mzhelskiy** [comment]
В плагине это достаточно просто сделать самостоятельно:
```
array(
 'one' => 111,
 'cart' => include('ru.cart.php'),
);
```

**Comment by psnet** [comment]
Можно все сделать самостоятельно, да. В данном случае предложение чтобы все это происходило более удобно.

**Comment by kerbylav** [comment]
Ну тут я с Максимом согласен - лишний код, лишние проверки в движке для ситуаций, которые контролируются разработчиком плагинов, при чем плагинов больших, т.е. человек, по идее, знает, что делает. Другое дело, что этот "трюк" внести в описание.

**Comment by psnet** [comment]
>Другое дело, что этот "трюк" внести в описание.

Ну вот хоть это. А вообще, получается, да, @kerbylav , вы правы
