### ISSUE TITLE
Добавить возможность добавления атрибутов async и defer для скриптов

### ISSUE THREAD

**Issue by psnet** [livestreet/livestreet#604]
Выделять такие скрипты из общей сжатой кучи в отдельные файлы.
Итого может быть три разных файла скриптов (в порядке приоритета загрузки):
- обычные (те, что есть сейчас)
- сжатая куча с атрибутом ```async```
- сжатая куча с атрибутом ```defer```

**Comment by kerbylav** [comment]
Кстати вот буквально сегодня хотел предложить какую-то группировку скриптов которые бы не в header'е подключать, а в конце страницы.

Вообще, по-хорошему, надо стараться загрузку большинства скриптов вниз переместить. Да, это  потенциально проблема для всякого inline-кода, но это не хорошая практика, от которой надо все равно избавляться.

**Comment by psnet** [comment]
По сути ничего (на сегодняшний день) переносить в конец страницы уже не нужно - атрибут ```defer``` у скрипта сделает это лучше.

**Comment by kerbylav** [comment]
Ну да, с этим предложением перенос в конец страницы не актуален.

**Comment by deniart** [comment]
Хорошая идея, для всяких скриптов шаринга будет самое то.

**Comment by mzhelskiy** [comment]
fix https://github.com/livestreet/livestreet-framework/commit/c9c28990dc657bd5e3373581a6915aa21b5f1c7e

**Comment by lifecom** [comment]
Хотелось бы уточнить:
Все js с параметром async (или defer) окажутся в одной куче?
Можно ли создать более одной кучи с параметром async (или defer)?
Что произойдет с файлом с параметрами 'merge'=>false и 'async'=>true?
Что произойдет, если будет прописано 'async'=>true и 'defer'=>true?
А что если сделать 'type'=>async (или defer)?

**Comment by lifecom** [comment]
> Можно ли создать более одной кучи с параметром async (или defer)?
Этот вопрос к тому, что есть "кучки" необходимые для отображения страницы и "кучки" функциональные...
