### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by psnet** [livestreet/livestreet#605]
https://github.com/livestreet/livestreet/blob/master/application/classes/modules/property/entity/ValueTypeFile.entity.class.php#L78
```
if ($iSizeKb = $oProperty->getValidateRuleOne('size_max') and $iSizeKb * 1025 < $sFileSize) {
```
скрытый смысл в "1025" байт на кб? **1024**

как и комментарий выше
>На ограни**еч**ение по размеру файла

**Comment by mzhelskiy** [comment]
пулреквест
