### ISSUE TITLE
Вместо иконок использовать шрифт

### ISSUE THREAD

**Issue by mzhelskiy** [livestreet/livestreet#608]
Предлагаю вместо icons.png использовать шрифт http://getbootstrap.com/components/#glyphicons

**Comment by lifecom** [comment]
мое мнение - лучше font awesome http://fortawesome.github.io/Font-Awesome/
т.к. с glyphicons у меня были проблемы с firefox

**Comment by psnet** [comment]
Ещё вопрос по лицензиям. Глифы только с активной ссылкой, но там есть дырка в лицензии что можно без ссылки если шрифты используются "из комплекта бутстрапа", это достаточно в описание проекта указать и можно без ссылки.

По поводу лиценизии авсом шрифтов нужно смотреть.

**Comment by deniart** [comment]
Уже был подобный тикет https://github.com/livestreet/livestreet/issues/413

**Comment by mzhelskiy** [comment]
Я так понял в том китете имелось ввиду заюзать инлайн base-код , а не шрифт

**Comment by ve1ikiy** [comment]
glyphicons не отображаются на WindowsPhone 8 и Kindle Fire =)

**Comment by psnet** [comment]
Плохо только что имена иконок не совместимы
