### ISSUE TITLE
Есть ли в планах обновить Smarty до 3 версии?

### ISSUE THREAD

**Issue by lifecom** [livestreet/livestreet#609]

**Comment by kerbylav** [comment]
Это шутка?

**Comment by lifecom** [comment]
пардон, ступил...

**Comment by sgavka** [comment]
Всё так надо обновиться к следующим версиям. Например, модификатор capitalize в 3.1.8 не очень верно работает с русским текстом (вместе с <PHP5.5). А в последней релизной версии всё работает (3.1.21).

**Comment by mzhelskiy** [comment]
В последних версиях смарти есть проблема - они заблокировали динамическое формирование подключаемых файлов внутри блоков. Это архитектурный недостаток 3 смарти, но в 3.1.8 данный момент работает, хоть и с небольшим "косяком".

**Comment by sgavka** [comment]
Для себя я "пофиксил" проблему с capitalize в 3.1.8. Просто заменил этот файл файлом из 3.1.21.
