### ISSUE TITLE
Поддержка getDisplayName() пользователя в автокомплитерах, почте и т.п.

### ISSUE THREAD

**Issue by kerbylav** [livestreet/livestreet#612]
Понятно, что раз везде на сайте будет "светиться" информация полученная через getDisplayName() то и в автокомплитерах и в поиске пользователей нужно, чтобы поиск был по этому самому getDisplayName()

У себя я это реализовывал путем использования user_profile_name для этой цели, т.е. при сохранении пользователя user_profile_name перезаписывался getDisplayName() и все поиски шли еще и по user_profile_name кроме логина, а в автокомплитерах возвращался getDisplayName() и в скобках логин пользователя, чтобы можно было отличить одного Васю Пупкина от другого и для того, чтобы парсить это дело, чтобы вычленить логин пользователя для использования, скажем, в почте.

**Comment by mzhelskiy** [comment]
Автокомплитеры юзеров постарались переделать на возврат id и getDisplayName
сама логика поиска не менялась
