### ISSUE TITLE
Не добавляется превью в новый топик

### ISSUE THREAD

**Issue by leealexey** [livestreet/livestreet#622]
После загрузки изображения в модальном окне, невозможно выбрать загруженную картинку. При клике на кнопку "выбрать" в консоль выводится ошибка:

Uncaught Error: cannot call methods on lsUploaderFile prior to initialization; attempted to call method 'getState'

Если закрыть это окно и сохранить топик как есть и открыть его для редактирования, то в модальном окне превью появляются загруженные ранее картинки и их уже возможно выбирать в качестве превью.

![screenshot]
(http://5sov.plumy.ru/preview.png)

**Comment by mzhelskiy** [comment]
на какой версии проверялось?
в текущей этого не должно быть

**Comment by leealexey** [comment]
на последней, ставил из этого архива http://livestreetcms.ru/uploads/ls_last.zip позавчера. Могу дать логин/пас на установленный движок.

**Comment by mzhelskiy** [comment]
там сборка ежедневная (по ночам), соответственно ставилась от 12 числа, а как раз 13 были фиксы медиа. Желательно скачать текущую сборку и проверить (у меня работает)

**Comment by leealexey** [comment]
я могу просто перезаписать все файлы на сервере содержимым архива (кроме конфигов) без необходимости заново устанавливать движок?

**Comment by mzhelskiy** [comment]
да, но желательно удалить сначала старые файлы

**Comment by leealexey** [comment]
подтверждаю, баг пофиксен :)
