### ISSUE TITLE
Вынести перечисление в член класса

### ISSUE THREAD

**Issue by psnet** [livestreet/livestreet#623]
https://github.com/livestreet/livestreet/blob/198b087a985a7045ade4ec5b2a4e75e2dc28cda5/application/classes/modules/media/Media.class.php#L186
```array('jpg', 'jpeg', 'gif', 'png')```
чтобы можно было расширять

**Comment by mzhelskiy** [comment]
Расширение идет как раз через переопределение метода GetMediaTypeByFileExtension
