### ISSUE TITLE
Не работает logout

### ISSUE THREAD

**Issue by leealexey** [livestreet/livestreet#630]
Сборка скачана только что, после авторизации не удается выйти, выбрасывает 404 ошибку а в урле остается security key
Выйти получается только удалением кук.

**Comment by mzhelskiy** [comment]
Не могу воспроизвести - выходит нормально

**Comment by leealexey** [comment]
http://5-sov.ru/
admin
admin

**Comment by leealexey** [comment]
еще попутно вопрос, в админке пользователей можно назначить админами?

**Comment by mzhelskiy** [comment]
На сайте стоит не дефолтная версия + она не последняя

**Comment by leealexey** [comment]
т.е. проблема в шаблоне?

**Comment by mzhelskiy** [comment]
я не знаю
предлагаю загрузить текущую версию с гитхаба и проверить

**Comment by leealexey** [comment]
Хорошо, а как проще всего отслеживать изменения в дефолтном шаблоне, чтобы я мог вносить правки в свой кастомный шаблон?

**Comment by mzhelskiy** [comment]
все изменения доступны здесь https://github.com/livestreet/livestreet/commits/master/application/frontend/skin/developer

**Comment by leealexey** [comment]
Спасибо Макс :)
