### ISSUE TITLE
Дублирование запросов при создании/обновлении опроса

### ISSUE THREAD

**Issue by mzhelskiy** [livestreet/livestreet#631]
Форма создания опросов при отправке отправляет сразу два одинаковых ajax запроса, в итоге создается два одинаковых опроса. Тоже самое при редактировании.

**Comment by deniart** [comment]
Вроде все нормально работает.

**Comment by deniart** [comment]
Пардон, в firefox'e баг есть.

**Comment by deniart** [comment]
Fixed https://github.com/livestreet/livestreet-framework/commit/f6e6927b7ac9f2ae4af72d3251c412a84862cbbb
