### ISSUE TITLE
Вынести макс. количество подаваемых объектов в рсс в конфиг

### ISSUE THREAD

**Issue by psnet** [livestreet/livestreet#632]
ActionRss.class.php

Для всех лент задано ровно две страницы объектов:
```php
 $aResult = $this->Topic_GetTopicsGood(1, Config::Get('module.topic.per_page') * 2, false);
```
https://github.com/livestreet/livestreet/blob/master/application/classes/actions/ActionRss.class.php#L70

https://github.com/livestreet/livestreet/blob/master/application/classes/actions/ActionRss.class.php#L112

https://github.com/livestreet/livestreet/blob/master/application/classes/actions/ActionRss.class.php#L158

https://github.com/livestreet/livestreet/blob/master/application/classes/actions/ActionRss.class.php#L211

https://github.com/livestreet/livestreet/blob/master/application/classes/actions/ActionRss.class.php#L254

https://github.com/livestreet/livestreet/blob/master/application/classes/actions/ActionRss.class.php#L300

https://github.com/livestreet/livestreet/blob/master/application/classes/actions/ActionRss.class.php#L345

https://github.com/livestreet/livestreet/blob/master/application/classes/actions/ActionRss.class.php#L353

Можно количество страниц вывести в конфиг.

**Comment by Chiliec** [comment]
Единственное что там есть не только topic, но и comment. Единой настройкой для обоих вариантов?

**Comment by psnet** [comment]
Думаю, что для всех разделов топиков, страницы комментариев и комментариев топика будет достаточно.

**Comment by Chiliec** [comment]
Мне кажется одной настройки для всех лент было бы достаточно. Вообще RSS опять же пользователям не нужен. Их старательно лишают читалок что Гугл, что Яндекс, что и ускоряет увядание этой технологии для получения контента. И уж тем более какие-то специфичные ленты (не топики). Так что в принципе можно оставить как есть. 
![И так сойдет](https://cloud.githubusercontent.com/assets/982358/6419652/b358e790-bee0-11e4-99c8-698bfe78db14.jpeg)

**Comment by psnet** [comment]
Вот только экспорт из сайта, например, в твиттер проще всего настроить через рсс.

**Comment by Chiliec** [comment]
Согласен что проще, но лучше это делать через API. И зачем кучу параметров добавлять для количества элементов вывода? Твиттер поток с любым количеством элементов устроит.

**Comment by psnet** [comment]
АПИ нет. а РСС уже есть. 

>Твиттер поток с любым количеством элементов устроит.

так а если хочется отдать ему больше чем 2 страницы?

**Comment by Chiliec** [comment]
По хорошему бы наверное надо сделать модуль RSS, а то как-то нелогично получается.

**Comment by psnet** [comment]
Там по сути нет кода как такового, получение топиков и заполнение переменных для шаблона.
