### ISSUE TITLE
Ввод ЧПУ в движок

### ISSUE THREAD

**Issue by psnet** [livestreet/livestreet#636]
Имхо, таки нужно ввести ЧПУ для топиков в движок (транслит автогенерация на основе заголовка или поле ввода - включаемо в конфиге). Ведь мета описание, ключевые слова, каноничные урлы используются, а ЧПУ давно не новомодная вещь, но из того же ряда. Да, есть niceurl, но он слегка костыльный.

Предлагаю это прозрачно ввести в движок, а то есть rbac и другие крутые вещи, а чпу нет.

Урлы для топиков использовать, например:
```php
site.com/blog/%%любая_настраиваемая_строка_удобная_для_сео%%/ЧПУ
```
а ```%%любая_настраиваемая_строка_удобная_для_сео%%```, может содержать что угодно (имя блога, дату публикации, имя автора и т.п.), а сам поиск топика производить по последнему параметру - ``ЧПУ``

**Comment by Chiliec** [comment]
Согласен насчет ЧПУ из коробки, но поиск топика, как и вообще всех сущностей, везде завязан на id. Поэтому предлагаю:
```php
site.com/blog/%%любая_настраиваемая_строка_удобная_для_сео%%/id-ЧПУ.html
```
и тогда не придется ничего менять. Кроме того, можно будет сделать опциональным использование ЧПУ.

**Comment by psnet** [comment]
Ну или так (с ид).

**Comment by ve1ikiy** [comment]
я конечно не программист, но если в БД таблицы топиков есть столбец ид, то почему туда просто не добавить еще один столбец с ссылкой? Вызывать сам топик можно потом по ид, а ссылку формировать по столбцу с ЧПУ. Так сказать: "Говорим Ленин, подразумеваем - Партия"

**Comment by psnet** [comment]
@ve1ikiy  Так сложностей особых-то и нет с реализацией. Вопрос в том, что вроде как пора этому быть в движке.

**Comment by ve1ikiy** [comment]
@psnet если в 2.0 появится ЧПУ которое не вызывает конфликтов в плагинах я буду только рад. Мой предыдущий ответ был @Chiliec - ведь если все завязано на ид, то пускай так и остается, просто добавить топику еще один параметр вроде как не должно вызвать больших сложностей.
Все манипуляции делать с ид, а ссылку формировать из отдельной ячейки бд.

**Comment by prokopov-nikolai** [comment]
С точки зрения продвижения, чем меньше вложенность урла, тем легче его продвинуть. По этой причине по возможности идеальным будет урл /chpy/.
По возможности желательно предусмотреть настройку структуры урла, чтобы каждый мог определить оптимальный для себя.

**Comment by Chiliec** [comment]
@ve1ikiy верно, я ровно это и предлагаю.

Ещё я тут подумал, что ведь теперь у топика может быть несколько блогов. Как быть с ЧПУ? Брать первый или может вообще убрать название блога из УРЛ, как на том же хабре (только там без ЧПУ). Вот так:
```php
site.com/blog/id-ЧПУ.html
```

@prokopov-nikolai пруф насчет вложенности. Лично я такого не замечал.

**Comment by ve1ikiy** [comment]
@Chiliec после определенного количества символов соцсети и поисковики попросту обрезают ссылку, а вот точное количество символов не скажу, но сам с таким встречался когда настраивал чпу на вордпрессе. _(это по поводу вложенности в комментарии @prokopov-nikolai )_

Кстати, насчет вордпресса. Как по мне, там самая удобная настройка ЧПУ.

В формировании самой ссылки на пост лучше или оставить как есть, или добавить какую-то константу. К примеру на хабре  - /post/234324/ . 
Но зачем делать две переменные (blog+%задаваемая%), как предлагает @psnet ? Это вроде лишнее. :horse: 

* http://livestreet.ru/blog/admin/test.html (дублирование)
* http://livestreet.ru/admin/test.html (красиво)
* http://livestreet.ru/pron/sasha-grey-vernulas.html (хорошая новость)
* http://livestreet.ru/scandal/id-335-sasha-grey-vernulas.html (с ид+переменной -- дублирование)
* http://livestreet.ru/id-335-sasha-grey-vernulas.html (просто с ид норм)

**Обобщу.**
1)По умолчанию (сразу после установки) лучше оставить вид site.ru/id-334-test.html
2)Предусмотреть возможность формирования url с помощью префиксов (но тогда не использовать id, а брать только чпу-юрл)

* _site.ru/id-334-testing.html_
* _site.ru/%любой-настраиваемый-префикс%/testing.html_

**Comment by Chiliec** [comment]
@ve1ikiy не, @prokopov-nikolai говорит именно о сложности продвижения больших урл, а не отображении их в сниппете. Это совершенно разные вещи.

Надо дождаться ответа Максима, а то он может сказать что всё что мы здесь обсуждаем и не нужно вовсе.

**Comment by ve1ikiy** [comment]
@Chiliec большие url просто плохо распознаются поисковиками, поэтому их и сложно продвигать) 

@mzhelskiy а что вы думаете на этот счет?

**Comment by Chiliec** [comment]
@ve1ikiy ну зачем эти голословные заявления? Я много лет занимался SEO и могу сказать что никаких проблем с большими URL у меня никогда не возникало и никогда о таком даже не слышал. Всё это на уровне непонятно откуда берущихся слухов и заблуждений и не более.
Как пользователю да, мне больше нравятся короткие URL на латинице, а вот для ПС это не имеет совершенно никакого значения.
