### ISSUE TITLE
Ругается на render()

### ISSUE THREAD

**Issue by gabrin** [livestreet/livestreet#637]
При установке ругается на 
Fatal error: Call to a member function render() on a non-object in .../framework/classes/modules/viewer/Viewer.class.php on line 1272

При удалении куска кода из Viewer.class.php все работает
<addr>
/**
         * Через хук добавляем данные Open Graph
         */
        $_this = $this;
        $this->Hook_AddExecFunction('template_html_head_end', function () use ($_this) {
            return $_this->oOpenGraph->render();
        }, 10000);

Строки 1267-1273

**Comment by mzhelskiy** [comment]
какая версия php?
если после ``$this->MenuVarAssign();`` вставить  ``var_dump($this->oOpenGraph->render());`` - падает с ошибкой?

**Comment by gabrin** [comment]
Версия PHP 5.3
При вставке var_dump($this->oOpenGraph->render()); :+1: 
string(376) " " 
Fatal error: Call to a member function render() on a non-object in .../framework/classes/modules/viewer/Viewer.class.php on line 1274

**Comment by mzhelskiy** [comment]
если после этой строки https://github.com/livestreet/livestreet-framework/blob/master/classes/modules/viewer/Viewer.class.php#L179  вставить ``var_dump($this->oOpenGraph);`` ?

**Comment by gabrin** [comment]
Тогда все ок.

**Comment by mzhelskiy** [comment]
в смысле не возникает ошибки (выводит объект?) или начинает работать и удаленный ранее код?

**Comment by gabrin** [comment]
При вставке работает все нормально без удаления кода.

**Comment by mzhelskiy** [comment]
тогда не могу понять причину проблемы

**Comment by DenisKhomusyak** [comment]
object(ModuleViewer_EntityOpenGraph)#22 (7) { ["_aData":protected]=> array(0) { } ["sPrimaryKey":protected]=> NULL ["aValidateRules":protected]=> array(0) { } ["aValidateErrors":protected]=> array(0) { } ["sValidateScenario":protected]=> string(0) "" ["aBehaviors":protected]=> array(0) { } ["_aBehaviors":protected]=> NULL } 
Fatal error: Call to a member function render() on a non-object in \framework\classes\modules\viewer\Viewer.class.php on line 1273
--------------------------------------
вот выводит объект с нулевыми свойствами.В чем трабл?

**Comment by DenisKhomusyak** [comment]
```
object(ModuleViewer_EntityOpenGraph)#22 (7) { ["_aData":protected]=> array(0) { } ["sPrimaryKey":protected]=> NULL ["aValidateRules":protected]=> array(0) { } ["aValidateErrors":protected]=> array(0) { } ["sValidateScenario":protected]=> string(0) "" ["aBehaviors":protected]=> array(0) { } ["_aBehaviors":protected]=> NULL }
``` 
```
Fatal error: Call to a member function render() on a non-object in \framework\classes\modules\viewer\Viewer.class.php on line 1273
```

**Comment by mzhelskiy** [comment]
Есть возможность дать доступ к площадке с сайтом?

**Comment by DenisKhomusyak** [comment]
Какие образом?Он на локалке у меня)Если только через teamviewr

**Comment by mzhelskiy** [comment]
Если локальный, то можно через Google Chrome и этот плагин https://chrome.google.com/webstore/detail/chrome-remote-desktop/gbchcmhmhahfdphkhkmpfmihenigjmpp

**Comment by DenisKhomusyak** [comment]
сейчас

**Comment by DenisKhomusyak** [comment]
509985152781

**Comment by mzhelskiy** [comment]
fix https://github.com/livestreet/livestreet-framework/commit/36fade927882dcabc0dcd414bbcf5b514802fafd
