### ISSUE TITLE
iframe в Jevix

### ISSUE THREAD

**Issue by leealexey** [livestreet/livestreet#640]
Обнаружилось странное поведение парсера. Съедает src из этого кода:

    <iframe src="//vk.com/video_ext.php?oid=145083501&id=171284354&hash=2b113e1421b036e3&hd=1" width="640" height="360"  frameborder="0"></iframe>

Через плагин добавил vk.com во все секции с "#domain"

        $cfgAllowTagParamsData = Config::Get('jevix.default.cfgAllowTagParams.3.1.data.#domain');
        $cfgAllowTagParamsData[] = 'vk.com';
        $cfgAllowTagParamsSrc = Config::Get('jevix.default.cfgAllowTagParams.5.1.src.#domain');
        $cfgAllowTagParamsSrc[] = 'vk.com';
        $cfgAllowTagParamsSrc2 = Config::Get('jevix.default.cfgAllowTagParams.8.1.src.#domain');
        $cfgAllowTagParamsSrc2[] = 'vk.com';
        $cfgSetTagParamCombination = Config::Get('jevix.default.cfgSetTagParamCombination.0.2.movie.value.#domain');
        $cfgSetTagParamCombination[] = 'vk.com';

        Config::Set('jevix.default.cfgAllowTagParams.3.1.data.#domain', $cfgAllowTagParamsData);
        Config::Set('jevix.default.cfgAllowTagParams.5.1.src.#domain', $cfgAllowTagParamsSrc);
        Config::Set('jevix.default.cfgAllowTagParams.8.1.src.#domain', $cfgAllowTagParamsSrc2);
        Config::Set('jevix.default.cfgSetTagParamCombination.0.2.movie.value.#domain', $cfgSetTagParamCombination);

**Comment by mzhelskiy** [comment]
Нужно добавить те же самые параметры через конфиг config.jevix.php и проверить

**Comment by leealexey** [comment]
Создал файл config.jevix.php в application/config и добавил в него параметры - не сработало. Может быть я не так понял?

**Comment by psnet** [comment]
А с протоколом работает?

**Comment by leealexey** [comment]
С протоколом так же

        $cfgAllowTagParamsData = Config::Get('jevix.default.cfgAllowTagParams.3.1.data.#domain');
        $cfgAllowTagParamsData[] = 'https://vk.com';
        $cfgAllowTagParamsSrc = Config::Get('jevix.default.cfgAllowTagParams.5.1.src.#domain');
        $cfgAllowTagParamsSrc[] = 'https://vk.com';
        $cfgAllowTagParamsSrc2 = Config::Get('jevix.default.cfgAllowTagParams.8.1.src.#domain');
        $cfgAllowTagParamsSrc2[] = 'https://vk.com';
        $cfgSetTagParamCombination =    Config::Get('jevix.default.cfgSetTagParamCombination.0.2.movie.value.#domain');
        $cfgSetTagParamCombination[] = 'https://vk.com';

**Comment by psnet** [comment]
С указанием протокола в коде фрейма для вставки - будет работать.

**Comment by leealexey** [comment]
попробовал в коде и так

    <iframe src="https://vk.com/video_ext.php?oid=145083501&id=171284354&hash=2b113e1421b036e3&hd=1" width="640" height="360"  frameborder="0"></iframe>

и так

    <iframe src="//vk.com/video_ext.php?oid=145083501&id=171284354&hash=2b113e1421b036e3&hd=1" width="640" height="360"  frameborder="0"></iframe>

**Comment by psnet** [comment]
Первый вариант + добавьте домены прямо в конфиг вручную и проверьте работу.

**Comment by leealexey** [comment]
Сейчас опытным путем выяснил, если в файле /framework/config/jevix.php vk.com добавлять в массивы последним или первым элементом (даже руками, а не плагином), то код не работает.

        ('#domain' => array('vk.vom', 'youtube.com', 'rutube.ru', 'vimeo.com'))

а если заменить  'youtube.com' на 'vk.vom' то работает!
не понимаю почему так.

**Comment by psnet** [comment]
Потому что ```vk.vom``` - vk.**V**OM
протокол в конфиге указывать не нужно, в том месте только домены, а протоколы в конфиге указываются отдельно. а вот в фрейме протокол нужен

**Comment by leealexey** [comment]
ёмоё, исправил опечатку, работает. Но в плагине то опечатки не было, почему через плагин не получается добавить этот домен?

        $cfgAllowTagParamsData = Config::Get('jevix.default.cfgAllowTagParams.3.1.data.#domain');
        $cfgAllowTagParamsData[] = 'vk.com';
        $cfgAllowTagParamsSrc = Config::Get('jevix.default.cfgAllowTagParams.5.1.src.#domain');
        $cfgAllowTagParamsSrc[] = 'vk.com';
        $cfgAllowTagParamsSrc2 = Config::Get('jevix.default.cfgAllowTagParams.8.1.src.#domain');
        $cfgAllowTagParamsSrc2[] = 'vk.com';
        $cfgSetTagParamCombination = Config::Get('jevix.default.cfgSetTagParamCombination.0.2.movie.value.#domain');
        $cfgSetTagParamCombination[] = 'vk.com';

        Config::Set('jevix.default.cfgAllowTagParams.3.1.data.#domain', $cfgAllowTagParamsData);
        Config::Set('jevix.default.cfgAllowTagParams.5.1.src.#domain', $cfgAllowTagParamsSrc);
        Config::Set('jevix.default.cfgAllowTagParams.8.1.src.#domain', $cfgAllowTagParamsSrc2);
        Config::Set('jevix.default.cfgSetTagParamCombination.0.2.movie.value.#domain', $cfgSetTagParamCombination);

**Comment by psnet** [comment]
Последовательно отладчиком сравнивайте результат после каждого ```Config::Set``` что получилось в ```Config::Get('jevix.default')```

**Comment by leealexey** [comment]
Спасибо за помощь, ошибка в моей невнимательности :( Я перезаписывал измененный jevix дефолтным jevix'om который хранился в другой переменной.
