### ISSUE TITLE
Остатки лоадера после ошибок при загрузке пустых потоков

### ISSUE THREAD

**Issue by kerbylav** [livestreet/livestreet#642]
![fee029d556 1](https://cloud.githubusercontent.com/assets/1224839/6653278/0f9a20e8-ca9c-11e4-9070-dc9af5e8475d.jpg)

**Comment by mzhelskiy** [comment]
Какая версия? Я недавно это фиксил

**Comment by mzhelskiy** [comment]
Так что?

**Comment by kerbylav** [comment]
Да, сейчас все хорошо
