### ISSUE TITLE
Баги верстки

### ISSUE THREAD

**Issue by psnet** [livestreet/livestreet#647]
![default](https://cloud.githubusercontent.com/assets/1023918/6998968/dffa099e-dbfc-11e4-9db5-b4313859ca25.png)

**Кликабельно**

1. Плохо читается надпись
2. В скруглениях белые уголки

ФФ 37

**Comment by deniart** [comment]
1. ОС? Сглаживание шрифтов отключено?

**Comment by psnet** [comment]
в7, да
