### ISSUE TITLE
Выход

### ISSUE THREAD

**Issue by prokopov-nikolai** [livestreet/livestreet#650]
Не получается разлогиниться когда сайт в закрытом режиме работает.
Видимо всему причиной 
$config['general']['close_exceptions'] = array(
    'auth',
    'ajax' => array('captcha'),
); // список action/avent для исключения при закрытом режиме

Наверно это должно быть включено по умолчанию.

**Comment by mzhelskiy** [comment]
Эти настройки как раз для решения подобных проблем.
Проверил - у меня работает.
Что именно у тебя происходит при попытки выйти?

**Comment by prokopov-nikolai** [comment]
Выдает 404 ошибку.

1. Отключил все плагины.
2. Перенес в конфиг локал 
$config['general']['close'] = true; // использовать закрытый режим работы сайта, сайт будет доступен только авторизованным пользователям
$config['general']['close_exceptions'] = array(
	'auth',
	'ajax' => array('captcha'),
	''
); // список action/avent для исключения при закрытом режиме

3. Жму выход. Перикидывает на страницу /login/exit/?security_ls_key=e6412b32a8bd8cf838f2bcc1fdb4abe5

4. Захожу в ActionAuth в Init. В начале пишу exit. Не попадает в Экшен.

**Comment by prokopov-nikolai** [comment]
Разобрался. Это у меня старый код. Сейчас должен быть auth
