### ISSUE TITLE
Ограничение на длину почты в инсталляторе.

### ISSUE THREAD

**Issue by mainefremov** [livestreet/livestreet#651]
Столкнулся с тем, что 20 символов оказалось мало.
До этого ни один сайт не ругался на такую проблему, то есть ограничение лишнее. Нужно менять.

**Comment by mzhelskiy** [comment]
а нет такого ограничения
нужно больше подробностей

**Comment by mzhelskiy** [comment]
проблема была не в инсталляторе, а в форме авторизации
fix
