### ISSUE TITLE
Селекторы в wall.js

### ISSUE THREAD

**Issue by mzhelskiy** [livestreet/livestreet#652]
Здесь https://github.com/livestreet/livestreet/blob/master/application/frontend/components/wall/js/wall.js#L89-L91  несуществующие селекторы, в итоге они затирают их в wall-entry.js
По коду ниже есть еще левые селекторы.

**Comment by mzhelskiy** [comment]
из-за этого не работает удаление и ответ у сообщений

**Comment by mzhelskiy** [comment]
вот еще селектор https://github.com/livestreet/livestreet/blob/19e6a64b4be1cb862720d3427d43c99318f5d167/application/frontend/components/wall/js/wall.js#L154

**Comment by deniart** [comment]
Поправил
