### ISSUE TITLE
Чужие фото в галерее

### ISSUE THREAD

**Issue by rsmike** [livestreet/livestreet#658]
Тег gallery items принимает "чужие" id фотографий, а не только те, что были загружены через загрузку медиа.

**Comment by mzhelskiy** [comment]
Проверялось от имени админа? У него есть доступ ко всем фото.

**Comment by rsmike** [comment]
Нет, не админа. 
- регистрируем обычного нового пользователя на демо-сайте альфы LS
- вставляем в топик галерею через медиа-загрузчик (допустим, загружено две фото)
- в сгенерированный тег gallery добавляем кроме этих двух id все числа подряд
- получаем на выходе галерею с фоточками других пользователей.

**Comment by mzhelskiy** [comment]
Туда попадали только те фото юзеров, которые так и не создали свой топик, т.е. не привязанные к конкретному объекту. Пофиксил.
