### ISSUE TITLE
В админке движка (!) в "Управление плагинами" доступно обновление даже если его нет

### ISSUE THREAD

**Issue by psnet** [livestreet/livestreet#661]
Кнопка "Применить обновление" есть, когда обновлять-то нечего.

**Comment by mzhelskiy** [comment]
Эта же кнопка есть в отдельной админке.
Она означает - применение обновлений (миграций) и прописывание версии плагина в БД.
Появляется она после заливки плагина в каталог с плагинами, его нужно переактивировать или применить обновление.

**Comment by psnet** [comment]
Но по факту логики обновления-то нет, это инициализация.

**Comment by mzhelskiy** [comment]
не важно как это называется, главное, чтобы это была одна кнопка, а не две (обновить, инициализировать и прочее). Кнопка, которая актуализирует БД плагина и сбросит кеш.

**Comment by psnet** [comment]
Все равно *дикость*
