### ISSUE TITLE
Забыли про nested set комментарии (постраничную навигацию по комментариям)

### ISSUE THREAD

**Issue by psnet** [livestreet/livestreet#663]
- Нету пагинации для комментариев, если выставить число на страницу

``` php
$config['module']['comment']['nested_per_page'] = 3;    // Число комментов на одну страницу в топике, актуально только при use_nested = true
```
- Решить полу-баг-фичу ещё от 1.0.3:
  если выставить

``` php
$config['module']['comment']['nested_page_reverse'] = false;    // Определяет порядок вывода страниц. true - последние комментарии на первой странице, false - последние комментарии на последней странице
```

то порядок страниц идет наоборот т.е. `4, 3, 2, 1`, но так даже пагинация у топиков себя не ведет, имхо, нужно для стандартизации придерживаться единого вида пагинации: от 1 слева и до макс. страницы справа.

**Comment by psnet** [comment]
**UPD**:

- Также в лс 1.0.3 забыли в постраничной навигации про параметр `sBaseUrl` вообще, который формирует `Viewer_MakePaging`, поэтому там все ссылки на страницы комментариев объекта начинаются как `?cmtpage=2`

Ну вот в 2.0 нужно бы его добавить

**Comment by mzhelskiy** [comment]
> поэтому там все ссылки на страницы комментариев объекта начинаются как ?cmtpage=2

это сделано специально, чтобы не "ломать" чпу урлы топиков

**Comment by psnet** [comment]
>это сделано специально, чтобы не "ломать" чпу урлы топиков

а как же их можно "поломать"?

**Comment by mzhelskiy** [comment]
/mytopic.html/page2/

**Comment by psnet** [comment]
Это ты пример стандартной пагинации приводишь, а у комментариев там все по-другому и получилось бы:
```
/mytopic.html?cmtpage=2
```
и ничего не поломалось бы

**Comment by mzhelskiy** [comment]
на сколько помню, в 1.0 пагинация через Viewer могла быть только вида /pageN/

**Comment by psnet** [comment]
Вьюер сам заполняет только переменные, а урлы "/pageN/" строит пагинация, для топиков - это pagination.tpl, для комментариев - пагинация отдельная "comment_paging.tpl" и вот она строит урлы по-другому (коряво визуально даже).

**Comment by deniart** [comment]
@mzhelskiy Что тут нужно исправить? Насколько понял пагинация работает нормально, но комментарии всегда выводятся все -> проблема в бэкенде.
