### ISSUE TITLE
robots.txt - /tag/$

### ISSUE THREAD

**Issue by lifecom** [livestreet/livestreet#669]
А зачем закрывать теги от поисковиков? Чем это плохо?
У меня например, очень много переходов именно по тегам...

В тему:
http://hachu-site.ru/nuzhno-li-zakryivat-tegi-ot-indeksatsii-otvechaet-yandeks.html
http://kabanov.biz/saitostroitelstvo/nuzhno-li-zakryvat-stranitsy-tegov-ot-indeksatsii

**Comment by mzhelskiy** [comment]
На эту тему было много обсуждений на livestreet.ru
Пришли к мнению, что для индексации лучше открывать только конечный контент (топики), а не различные варианты списков контента.
