### ISSUE TITLE
Баг profile_photo_width

### ISSUE THREAD

**Issue by makenskiy** [livestreet/livestreet#670]
Версия LS 1.0.3. 

В конфиге настройка profile_photo_width не работает с размерами больше 1000. Если размер указан например в 2000, на выходе получаем фотографию 1000.

**Comment by mzhelskiy** [comment]
вот здесь нужно увеличить размер временной фото - https://github.com/livestreet/livestreet/blob/1.0.3/classes/actions/ActionSettings.class.php#L114

**Comment by makenskiy** [comment]
Спасибо!
