### ISSUE TITLE
Неисправна подгрузка в экшене people

### ISSUE THREAD

**Issue by lifecom** [livestreet/livestreet#671]
Замечено на демо:
Если нажать под списком пользователей "Подгрузить ещё" подгружаются еще 15 пользователей, т.е. как бы "2-я страница". При повторной подгрузке подгружается (дублируется) та же "2-я страница". И так до бесконечности - один и тот же список юзеров со "2-й страницы".

**Comment by venticello** [comment]
Загрузи последнюю версию, я писал про это, уже пофикшено, тоже самое было с блогами.

https://github.com/livestreet/livestreet-framework/commit/f322b3d3ac844211363552505514bf6af318ed4b
