### ISSUE TITLE
Исправить модуль Geo

### ISSUE THREAD

**Issue by psnet** [livestreet/livestreet#675]
В модуле `geo` при добавлении привязки гео данных к цели в `CreateTarget` идет проверка цели:
```php
        /**
         * Проверяем объект на валидность
         */
        if (!$this->CheckTarget($sTargetType, $iTargetId)) {
            return false;
        }
```
метод `CheckTarget` проверяет разрешен ли данный тип цели, а также делает проверку на существование цели (по ид):
```php
    public function CheckTarget($sTargetType, $iTargetId)
    {
        if (!$this->IsAllowTargetType($sTargetType)) {
            return false;
        }
        $sMethod = 'CheckTarget' . func_camelize($sTargetType);
        if (method_exists($this, $sMethod)) {
            return $this->$sMethod($iTargetId);
        }
        return false;
    }
```
первая проверка вопросов не вызывает, а вот проверка существования цели:
```php
        $sMethod = 'CheckTarget' . func_camelize($sTargetType);
        if (method_exists($this, $sMethod)) {
            return $this->$sMethod($iTargetId);
        }
```
идеологически не должна находится в данном модуле. **Валидацию цели по ид должен производить сторонний модуль (код), который и вызывает добавление привязки гео-объекта к цели. Сам гео модуль по идеологии не должен этого делать.**

Правки
---

- Таким образом метод `public function CheckTarget($sTargetType, $iTargetId)` из модуля `geo` приложения должен быть таким:
```php
    public function CheckTarget($sTargetType, $iTargetId)
    {
        return $this->IsAllowTargetType($sTargetType);
    }
```
- Также удалить метод `public function CheckTargetUser($iTargetId)` (автоматически формируемый) из данного модуля, т.к. использовался методом проверки для типа цели "юзер".

**Comment by mzhelskiy** [comment]
Такое поведение есть во многих модулях, предполагалось, что нужные методы проверки будут добавляться через наследование плагинами. Возможно стоит рассмотреть вариант с передачей нужных коллбеков в параметрах типов.

**Comment by psnet** [comment]
>что нужные методы проверки будут добавляться через наследование плагинами.

да, но это не правильно.
