### ISSUE TITLE
Перенести модуль Geo в фреймворк

### ISSUE THREAD

**Issue by psnet** [livestreet/livestreet#677]
Данный модуль вполне можно перенести в фреймворк, если выполнить правки #675 , а также
- либо убрать по-умолчанию заданный тип цели "пользователь" в `aTargetTypes` https://github.com/livestreet/livestreet/blob/master/application/classes/modules/geo/Geo.class.php#L52 и добавлять его в ините приложения
- либо убрать вообще контроль типа цели (`AddTargetType` и всю его команду)

**Comment by mzhelskiy** [comment]
Тоже самое можно сказать и о других модулях, например, property
Здесь скорее стоит подумать над созданием репо модулей.

**Comment by psnet** [comment]
А по какому принципу тогда делить модули фреймворк/приложение?

**Comment by mzhelskiy** [comment]
найти грань между системными вещами и приложением
