### ISSUE TITLE
Предложение: блоги из которых топики не будут отображаться на главной

### ISSUE THREAD

**Issue by venticello** [livestreet/livestreet#681]
Сделали, чтобы можно было поставить в топиках не выводить на главную никогда, более актуально мне кажется сделать и блоги из которых топики не будут попадать на главную.
Это позволит легко сделать "песочницу", всякие блоги с пиарами, флудом и так далее, которые не будут попадать в общую ленту.

**Comment by psnet** [comment]
Как опция в самом блоге?

**Comment by venticello** [comment]
Да, просто галочка при редактировании, если она установлена, то из этого блога топики никогда не попадут в главную ленту.

**Comment by psnet** [comment]
Хорошая идея :+1:
