### ISSUE TITLE
Выбор списка пользователей

### ISSUE THREAD

**Issue by mzhelskiy** [livestreet/livestreet#684]
Сейчас выбор юзеров в разных виджетах (письма, друзья и т.п.) происходит через логин, необходимо переделать на использование ID. Дополнительно использовать автокомплит для выбора списка юзеров (сейчас для этого есть js lsAutocompleteStrict и либа tag-it).

**Comment by psnet** [comment]
>Сейчас выбор юзеров в разных виджетах (письма, друзья и т.п.) происходит через логин, необходимо переделать на использование ID.

чтобы юзеры вводили ид пользователей?..
