### ISSUE TITLE
Постраничноть в выборе медиа из ранее загруженных

### ISSUE THREAD

**Issue by mzhelskiy** [livestreet/livestreet#685]
Сейчас для выбора используется подгрузка, а не постраничность. Это не удобно, т.к. нельзя сразу перейти, например, к первым загруженным фото - нужно прогрузить все предыдущие.
+ подумать над оформлением, т.к. сейчас окно со списком медиа занимать меньше половины всего попап-окна.

**Comment by deniart** [comment]
https://github.com/livestreet/livestreet-framework/commit/ad5724b7d3e392d96973b487290ed282fdbcacec
