### ISSUE TITLE
Отдельный виджет для управления медиа

### ISSUE THREAD

**Issue by mzhelskiy** [livestreet/livestreet#686]
Не хватает возможности вставить в произвольное место кнопку с вызовом окна медиа, где можно будет просмотреть имеющиеся изображения и загрузить новые. Без функций вставки.

**Comment by mzhelskiy** [comment]
А что за обработчик на /ajax/media/count/ ?

**Comment by deniart** [comment]
Должен возвращать кол-во загруженных файлов в переменной count
