### ISSUE TITLE
Разобраться с js .bind()

### ISSUE THREAD

**Issue by mzhelskiy** [livestreet/livestreet#689]
Текущая реализация .bind() некорректная. 
Подробнее здесь http://livestreet.ru/blog/sollutions/17939.html
Нормальная реализация - https://github.com/IonDen/ion.rangeSlider/blob/master/js/ion.rangeSlider.js#L38

**Comment by deniart** [comment]
> Текущая реализация .bind() некорректная

Текущая или та что в 1.0.3 ? Чем вариант по ссылке отличается от текущей реализации?

**Comment by mzhelskiy** [comment]
текущая реализация валит js ошибку при подключении твиттера (нужно убрать условие ``if ( ! Function.prototype.bind )`` если не из IE). В том топике есть пример кода на fiddle

**Comment by deniart** [comment]
Мы говорим про одну и ту же *текущую* реализацию? Я имею ввиду эту - https://github.com/livestreet/livestreet-framework/blob/master/frontend/components/ls-core/polyfills.js

> нужно убрать условие if ( ! Function.prototype.bind )

Зачем?

> В том топике есть пример кода на fiddle

Там полифил из лс 1.0.3

**Comment by mzhelskiy** [comment]
> Зачем?

для эмуляции IE  и воспроизведения ошибки

> Там полифил из лс 1.0.3

замени на текущий - результат не изменится

**Comment by deniart** [comment]
> замени на текущий - результат не изменится
http://jsfiddle.net/z89o15em/5/

**Comment by mzhelskiy** [comment]
зуб даю, что не работал пару месяцев назад, даже проверял с кодом от мозила.орг (собственно он совпадал с текущим)
возможно изменили скрипт твиттера
закрываю, но надо будет помониторить тот момент
