### ISSUE TITLE
Медиа, оригиналы

### ISSUE THREAD

**Issue by venticello** [livestreet/livestreet#704]
В медиа загружая изображение, по умолчанию вставка оригинала, при этом, оригинал может быть 5000х5000 для веб это перебор.
Предлагаю либо сделать возможность по-умолчанию выбирать какой то размер, либо сделать настройку при которой мы урезаем и оригинал до определенной нужной нам величины. Даже при том, что мы потом захотим сделать другие размеры изображений, нам вряд ли потребуются оригиналы 5000х5000 при том что они и место на сервере зря крадут. А если я задам, что мне по ширине макс нужны 1280, то и проблем не будет с хранением и вставка не так сильно будет страдать. Если не прав, поправьте.

**Comment by venticello** [comment]
Фотосет так же создается из оригиналов, а так средний вес файлов 1Мб, а в посте может быть несколько фотосетов. У меня пост с 15 картинками убивает Chrome на iphone 5s, т.е. открываешь страницу и вылетает программа.

**Comment by venticello** [comment]
В эту же тему, на аватарки блогов при загрузке больших фото накладывается 2 водяных знака.

**Comment by venticello** [comment]
И на превью топика, та же история, накладывается ватермарк 2 раза.

**Comment by mzhelskiy** [comment]
Не могу повторить по водяным знакам. Можешь скинуть свои настройки для воспроизведения?

**Comment by venticello** [comment]
```
$config['module']['image']['params']['default']['watermark_use'] = true;    // Использовать ватермарк или нет
$config['module']['image']['params']['default']['watermark_type'] = 'image'; // Тип: image - накладывается изображение. Другие типы пока не поддерживаются
$config['module']['image']['params']['default']['watermark_image'] = '___path.skin.web___/assets/images/watermark.png'; // Полный серверный путь до картинки ватермарка
$config['module']['image']['params']['default']['watermark_position'] = 'bottom-right'; // Значения: bottom-left, bottom-right, top-left, top-right, center
$config['module']['image']['params']['default']['watermark_min_width'] = 450; // Минимальная ширина изображения, начиная с которой будет наложен ватермарк
$config['module']['image']['params']['default']['watermark_min_height'] = 370; // Минимальная высота изображения, начиная с которой будет наложен ватермарк
```

**Comment by mzhelskiy** [comment]
У меня все ок - вотермарт один. Может плагины какие активны?

**Comment by venticello** [comment]
Специально скачал последнюю сборку, без плагинов, загружаю аватар к разделу, размером 500x500px, ватермарк полупрозрачный png, при превью обрезки уже двойной ватермарк.

**Comment by mzhelskiy** [comment]
Действительно, у меня была какая-то проблема (так и не понял) с вотермарками. Ошибку воспроизвел.
Для блогов и юзеров пофиксил, а вот для превью пришлось сохранять оригинал файла без наложения вотермарка. Потенциально это может быть проблемой для некоторых сайтов.

**Comment by venticello** [comment]
Да, работает, проблему вижу только в том, что в медиа фотосетах в большом просмотре используются оригиналы и соответственно те кто хотят сохранить принадлежность файла этого не смогут сделать. По и идее нужна возможность указывать размер файлов которые будут использоваться для просмотра увеличенных фотосетов, это актуально будет и для тех кто не хочет уменьшать оригиналы, но сделать возможность людям смотреть фотсеты не перегружая трафик оригиналами.
