### ISSUE TITLE
Поднятие планки до php 5.5

### ISSUE THREAD

**Issue by kerbylav** [livestreet/livestreet#706]
Поддержка php 5.4 заканчивается в сентябре. Любой уважающий себя провайдер должен давно уже иметь php 5.5, а устанавливать ЛС на говносервисы это... странно. Да и не уверен я, что еще остались провайдеры у которых нет php 5.5

Получается ЛС искусственно ограничивает своих разработчиков ради непонятных проблем, которые в принципе не должны уже существовать.

Я устал от array(), я хочу использовать трейты, уверен, что и для генераторов найдется место.

**Comment by psnet** [comment]
В лс уже есть поведения которые решают проблему множественного наследования, которую решали трейты.

**Comment by kerbylav** [comment]
Зачем использовать костыли, когда есть нативный механизм? Зачем оглядываться на платформы, одна из которых умерла уже больше года назад, а другая умрет еще **до** выхода ЛС 2.0? 

Ну да, еще пару лет назад теоретически можно было нарваться на мегаленивых провайдеров, но сейчас-то ситуация совсем другая.

**Comment by Chiliec** [comment]
Что-то ЛС перестал поспевать за развитием PHP :neutral_face:

**Comment by psnet** [comment]
Трейты - это же вставляемые чистые куски кода при компиляции!

**Comment by kerbylav** [comment]
@psnet 
> Трейты - это же вставляемые чистые куски кода при компиляции!

Я не говорю, что трейтами заменять поведения, но когда требуется функционал трейтов зачем прикручивать поведения?

**Comment by KarelWintersky** [comment]
Чем так плох `array()`, если не секрет? Несладкий?

**Comment by kerbylav** [comment]
@KarelWintersky Громоздкий. Пробовали писать сложные условия для фильтров ORM? Ну хотя бы вот элементарно сортировка 
```php
GetItemsByTypeIdInAndStatus(array(1,2,3),1,array('#order'=>array('title'=>'desc')))
```
и
```php
GetItemsByTypeIdInAndStatus([1,2,3],1,['#order'=>['title'=>'desc']])
```

Где лучше читаемость?

**Comment by psnet** [comment]
@kerbylav возможно, кстати, дело привычки, но вот пробелы после запятых - важно (psr-1)

**Comment by kerbylav** [comment]
@psnet PHPStorm для этого есть :)

**Comment by psnet** [comment]
@kerbylav да, но в вашем примере их нет) и вся красота новой записи массива теряется среди отсутствия пробелов)

**Comment by KarelWintersky** [comment]
@kerbylav лично мне кажется, что ради одной короткой записи массивов переходить на пхп 5.5 смысла нет. 

Да, сложные условия писать приходилось. И да, при этом я предпочитаю писать array() в явном виде. Потому что глаз по строке бежит и видит "ага, массив", определен явно. 

Массив как `[...]` - сахар.

**Comment by mzhelskiy** [comment]
Речи об одномоментном переписывании движка под 5.5 речи не идет, здесь скорее о минимальной планке, в которой комфортно будут чуствовать себя другие разработчики, разрабатывая плагины. В целом я поддерживаю ограничение минимальной от 5.5

**Comment by kerbylav** [comment]
@KarelWintersky Как сказал @mzhelskiy речь не идет о переписывании, но о поднятии минимальной планки. Вам удобно писать array(), мне - []. Возможно кому-то придется использовать сторонние библиотеки, кому-то нравятся генераторы, кто-то жить не может без finally. И ограничивать php 5.3 - это ограничивать разработчиков.

**Comment by psnet** [comment]
@mzhelskiy 
>В целом я поддерживаю ограничение минимальной от 5.5

Максим, только не нужно крайностей, очень много лет было 5.2, а потом бац - и сразу 5.5.
5.4 вполне хорошее разумное начало, следующая после 2-ки пусть будет и 5.5. для начала нужно выпустить версию, которой смогут однозначно пользоваться все. 5.4 откопает почти каждый, а 5.5. - не уверен.

Дело в том, что код лс не использует никакие другие возможности кроме как из 5.3 и то, только одны замыкания без пространств имен, например.

**Comment by venticello** [comment]
Пока выйдет 2.0 уже у большинства будет как раз php5.5, поддержка Debian 7 заканчивается в мае 2018, убунту 14.04 уже 5.5.9 версия у более низких версий ubuntu уже поддержка закончилась. Это самые популярные ОС для сервера, если кто то серьезный проект делает, он не будет делать его размещать на ОС без фиксов безопасности. А делать 5.4 для тех кто хочет просто поиграться и удалить нет смысла.
Разработчики Laravel вообще не переживают по этому поводу PHP >= 5.6.4, но делают они это явно из-за того, что хотят использовать в фреймворке передовые наработки, а не писать свои велосипеды. Сейчас тоже стал использовать Guzzle для работы со сторонними api, а там требование 5.5 к php.
