### ISSUE TITLE
Не работает изменение e-mail

### ISSUE THREAD

**Issue by fl32000** [livestreet/livestreet#707]
При смене пользователем e-mail, после перехода по ссылке в письме о подтверждении, возникает ошибка - Fatal error: Call to a member function getSession() on a non-object in /var/*****/data/www/*****.ru/application/tmp/templates/compiled/developer/725a4d90c8ac59e3bc64d15e5808da195643d691.file.block.user-photo.tpl.php on line 35

**Comment by deniart** [comment]
@mzhelskiy Нужно убрать вывод блоков в конфиге/бэкенде для ивентов `EventChangemailConfirmFrom`, `EventChangemailConfirmTo`
