### ISSUE TITLE
Медиа, количество изображений

### ISSUE THREAD

**Issue by venticello** [livestreet/livestreet#708]
Выделилась проблема, что пользователь может загрузить в топик неограниченное количество фотографий (вернее в медиа топика) и в итоге топик может быть в черновиках.
На практике у меня получилось, что человек загрузил 65 Мб фоток.
Проблема в том, что злоумышленник может просто вам убить место на сервере, а вы даже не поймете где искать.
Предлагаю сделать возможность ограничить загрузку определенного количества изображений к одной сущности, возможно даже рейтингом ограничивать.
Так же была проблема, при редактировании адимном чужого топика, нельзя удалить изображения из медиа.

**Comment by mzhelskiy** [comment]
по проблеме редактирования лучше создать отдельную задачу
