### ISSUE TITLE
Превью, не возможно удалить

### ISSUE THREAD

**Issue by venticello** [livestreet/livestreet#713]
При создании топика и загрузке превью, невозможно поменять или удалить до сохранения топика, после публикации превью можно менять.

**Comment by deniart** [comment]
У меня в новом топике нормально меняется/удаляется превью, но только если превью выбрано из только загруженных файлов, если выбирать из вкладки *Все* ранее загруженные файлы, то выдает ошибку:

```
System error
ActionAjax.class.php [ActionAjax->EventMediaCreatePreviewFile: 664]
```

**Comment by mzhelskiy** [comment]
> При создании топика и загрузке превью, невозможно поменять или удалить до сохранения топика, после публикации превью можно менять.

Такая проблема была, но я ее фиксил в последних коммитах

**Comment by mzhelskiy** [comment]
Вторая проблема это от сюда https://github.com/livestreet/livestreet/issues/690
