### ISSUE TITLE
Вынести формирование урл тегов в сущность

### ISSUE THREAD

**Issue by deniart** [livestreet/livestreet#725]
`{$tag->getUrl()}`

**Comment by mzhelskiy** [comment]
Метод добавил, нужно их в фронте прописать

**Comment by deniart** [comment]
Во фронте прописал, но тут https://github.com/livestreet/livestreet/commit/c95241c565ed1e8ddaf8002c0272ee198fde9cb2#diff-14cee1881e0f507abd36015eca202ea9L143 нужно чтобы `$topic->getTags()` и `favourite->getTags()` возвращали массив объектов, либо добавить другие методы в сущность. Еще на странице избранных топиков у тегов не выводится ссылка.
