### ISSUE TITLE
Отсутствие фильтрации входных данных

### ISSUE THREAD

**Issue by psnet** [livestreet/livestreet#727]
в `EventAjaxSubscribeToggle()` `ActionSubscribe.class.php` не имеет фильтрации входного параметра `value` что позволяет задавать его произвольные значения отличные от `1` и `0`. Да и вообще в проверку типа цели `Subscribe_CheckTarget` на существование передается "как есть".

**Comment by mzhelskiy** [comment]
вот же фильтрация https://github.com/livestreet/livestreet/blob/master/application/classes/actions/ActionSubscribe.class.php#L118

**Comment by psnet** [comment]
Точно
