### ISSUE TITLE
Ошибка при вставке изображения или галереи

### ISSUE THREAD

**Issue by Acode7** [livestreet/livestreet#728]
При включенном редакторе TinyMCE пытаемся вставить изображение, фотосет или ссылку. При нажатии на синюю кнопку "Вставить" никакой реакции не происходит (просто не работает).

**Comment by deniart** [comment]
Вставка фотосета в tinymce сейчас не работает, а вот все остальное должно нормально вставляться. Какой браузер?

**Comment by deniart** [comment]
Вставка фотосета поправлена https://github.com/livestreet/livestreet-framework/commit/8753ee8a30ec375eba71f21bc96f68c8090c54c2
