### ISSUE TITLE
Поиск, регистр

### ISSUE THREAD

**Issue by venticello** [livestreet/livestreet#733]
При поиске текст в базе приводится к нижнему регистру, а искомая фраза нет, соответственно если писать запрос словами с большой буквы ничего не найдет.

**Comment by mzhelskiy** [comment]
не могу понять почу так происходит, кодировка у таблицы регистро-независимая utf8_general_ci

**Comment by venticello** [comment]
Возможно когда в запросе явно приводят значение поля к нижнему регистру перестает такой быть, это как вариант.

**Comment by mzhelskiy** [comment]
проверил - не прокатило
