### ISSUE TITLE
Добавить возможность компилирования less и sass

### ISSUE THREAD

**Issue by lifecom** [livestreet/livestreet#734]
Например:
https://github.com/leafo/scssphp/
https://github.com/oyejorge/less.php

**Comment by kerbylav** [comment]
Ооо... На лету?!?? Зачем?!

**Comment by lifecom** [comment]
Чтобы можно было уже юзать, параллельно дожидаясь лучших времен...
Да и чем плохо делать это на лету!?

**Comment by deniart** [comment]
Лучше использовать gulp/grunt для этих целей (в пределах отдельных компонентов и шаблонов). Препроцессоры можно использовать хоть в ls 1.0, т.к. в итоге всеравно подключается скомпиленный css.
