### ISSUE TITLE
Модальные окна + ajax

### ISSUE THREAD

**Issue by lifecom** [livestreet/livestreet#735]
Возможно ли иметь один модальник на каждой странице и ajax-ом загружать в него нужный контент (remote data)? Ведь двух открытых одновременно модальников быть не может...

**Comment by Xmk** [comment]
Зачем это нужно?..
>Ведь двух открытых одновременно модальников быть не может...

Может и даже бывает...

**Comment by lifecom** [comment]
По моему мнению это нужно чтобы модальники не висели все время на странице в ожидании их вызова.

**Comment by mzhelskiy** [comment]
> По моему мнению это нужно чтобы модальники не висели все время на странице в ожидании их вызова.

так все-таки это причина? Или одновременно показывать (накладывать друг на друга) несколько модальных?
Если первое, то в LS давно есть возможность подгружать модальники через ajax.

**Comment by lifecom** [comment]
Вот что я имел ввиду:
На странице все время висит один модальник со своими header, body и footer. Но пустой.
При вызове нужного модальника - мы его открываем и наполняем нужным содержимым (через ajax?)...

**Comment by Xmk** [comment]
Он там не 1.
В чем смысл лишних ajax запросов для стат.данных?
Если хотите я могу вам плагин написать на заказ)

**Comment by lifecom** [comment]
Эти стат.данные могут использоваться, а могут и нет.
Например, если вы находитесь на странице пользователя, не означает то что вы обязательно захотите добавить его в друзья, тем самым вызывая модальник. А он висит в html, занимает место.

[Вот] (http://tutsme-webdesign.info/bootstrap-3-1-and-modals-with-remote-content/) пример того что я имею ввиду.

**Comment by mzhelskiy** [comment]
Уже писал выше - ls поддерживает ajax (загрузка модальника с содержимым) модальные окна.

**Comment by deniart** [comment]
Для подгрузки модальных есть js функция `ls.modal.load(url, ajax_params, modal_options)`, бэкенд должен отдавать html всего окна в переменной `sText` (не только текст/контент), пример можно тут посмотреть - https://github.com/livestreet/livestreet/blob/master/application/classes/actions/ActionAjax.class.php#L165-L179
