### ISSUE TITLE
Добавить подсветку комментариев пользователя

### ISSUE THREAD

**Issue by psnet** [livestreet/livestreet#736]
Добавить под комментарием кнопку подсветки всех комментариев пользователя в дереве.

**Comment by deniart** [comment]
Функционал полезный, но комментарии у нас итак перегружены различным функционалом, так что лучше оставить это плагинам.

**Comment by Xmk** [comment]
Вроде можно средствами css это реализовать + пару строчек js на переключение классов

**Comment by psnet** [comment]
@Xmk именно, также нужно добавить дата атрибуты с ид пользователя чтобы быстро находить комменты в дереве, это несложно.
