### ISSUE TITLE
Не отправляется личное сообщение

### ISSUE THREAD

**Issue by Acode7** [livestreet/livestreet#742]
В версии с последним комитом 3504 не работает отправка личного сообщения. На последней версии протестить не могу (сломался архив, подробнее в тикете 741)

**Comment by Acode7** [comment]
Дополнение. Причина ошибки - валидация форм на js.
Если убрать валидацию, письмо отправляет но возникает вторая проблема.

Ситуация.
1) Регистрируется пользователь
2) Админ пишет ему сообщение
3) Пользователь пытается ответить и не может, пишет об отсутствии прав на комментирование сообщений
application\classes\actions\ActionTalk.class.php
```
        if (!$this->ACL_CanPostTalkComment($this->oUserCurrent)) {
            $this->Message_AddErrorSingle($this->Rbac_GetMsgLast());
            return;
        }
```

**Comment by mzhelskiy** [comment]
Проверил на текущие git версии - письмо норм отправляется.
По поводу прав на комментирование - в системе по дефолту заведена роль "Пользователь", при регистрации она автоматом присваивается юзеру. У этой роли есть разрешение "комментить письма". Проверь этот момент.

**Comment by deniart** [comment]
@mzhelskiy Я временно закомментировал неработающий код.

**Comment by deniart** [comment]
Исправлено
