### ISSUE TITLE
Баг компонента radio

### ISSUE THREAD

**Issue by Acode7** [livestreet/livestreet#743]
При адаптации плагина обратной связи возникла ситуация:

Есть 3 поля radio
`            {component 'field'
                template = 'radio'
                classes = 'field-title ls-mb-10'
                value = 0
                checked = {( !$aFields.title ) ? true : false}
                id = 'field_title_no'
                name = "settings[field][title]"
                label = $aLang.plugin.my.contact.acp_field_hide}
            {component 'field'
                template = 'radio'
                classes = 'field-title ls-mb-10'
                value = 1
                checked = {( $aFields.title == '1' ) ? true : false}
                id = 'field_title_input'
                name = "settings[field][title]"
                label = $aLang.plugin.my.contact.acp_field_input}
            {component 'field'
                template = 'radio'
                classes = 'field-title'
                value = 2
                checked = {( $aFields.title == '2' ) ? true : false}
                id = 'field_title_list'
                name = "settings[field][title]"
                label = $aLang.plugin.my.contact.acp_field_list}`
Они всегда checked, даже если checked  = false или отсутствует.
Если 1 поле убрать, 2 других начинают корректно работать.
Источник бага тут:
\framework\frontend\components\field\field.radio.tpl
Срабатывает следующий код:
`{if {field_get_value form=$form name=$name} == 1}checked{/if}`
т.е. баг возникает при 3 и более элементов с одинаковым name, что может быть довольно часто

**Comment by deniart** [comment]
Поправил https://github.com/livestreet/livestreet-framework/commit/29596f6ace517dade1b0c7d7b5de542b83135350
