### ISSUE TITLE
Парсер текста

### ISSUE THREAD

**Issue by venticello** [livestreet/livestreet#751]
Почему в jevix не разрешен тег `<p>`? Ведь с ним удобнее оформлять топики.

**Comment by mzhelskiy** [comment]
Тег добавил - https://github.com/livestreet/livestreet-framework/commit/c52ad8c4833b7a85a45d1832ae1a24b4405cbd5a
Но чтобы парсер автоматически проставлял вместо br "p" нужно извращаться. Пока прокатит только для tinyMCE, для котрого можно включить расстановку P и отключить в парсере автоматические br.

**Comment by venticello** [comment]
Хотя бы вручную теперь можно, в идеале, чтобы абзац создавался при двух br подряд.
