### ISSUE TITLE
Медиа. Загрузка изображений

### ISSUE THREAD

**Issue by venticello** [livestreet/livestreet#755]
При загрузке изображений в медиа, сразу же показывается 100%, а потом генерит другие размеры изображений, указанные настройками, может сделать чтобы процентная шкала менялась после загрузки каждого размера, а то часто ощущение, что там что то зависло.

**Comment by Xmk** [comment]
![65%](http://clip2net.com/clip/m74337/1a128-clip-5kb.png)

Попробуйте файлик "потяжелей" залить ;)

**Comment by mzhelskiy** [comment]
Сделал чуть по другому - https://github.com/livestreet/livestreet-framework/commit/6356bef5db69816a14b694584a22734b41d04628
