### ISSUE TITLE
Обновление с 1.0.3

### ISSUE THREAD

**Issue by lifecom** [livestreet/livestreet#759]
Сегодня попробовал установить с обновлением с 1.0.3. Получил такую ошибку:
Duplicate column name 'user_id'
Incorrect datetime value: '0000-00-00 00:00:00' for column 'user_date_register' at row 1
Invalid default value for 'session_date_create'
Invalid default value for 'session_date_create'
Invalid default value for 'session_date_create'
Invalid default value for 'session_date_create'
Incorrect datetime value: '0000-00-00 00:00:00' for column 'user_date_register' at row 1
Can't DROP 'ls_blog_fk'; check that column/key exists
Can't DROP 'ls_blog_user_fk'; check that column/key exists
Can't DROP 'ls_blog_user_fk1'; check that column/key exists
Can't DROP 'ls_topic_comment_online_fk1'; check that column/key exists
Can't DROP 'ls_favourite_target_fk'; check that column/key exists
Can't DROP 'ls_favourite_tag_ibfk_1'; check that column/key exists
Can't DROP 'ls_friend_from_fk'; check that column/key exists
Can't DROP 'ls_friend_to_fk'; check that column/key exists
Can't DROP 'ls_geo_city_ibfk_1'; check that column/key exists
Can't DROP 'ls_geo_city_ibfk_2'; check that column/key exists
Can't DROP 'ls_geo_region_ibfk_1'; check that column/key exists
Can't DROP 'ls_geo_target_ibfk_1'; check that column/key exists
Can't DROP 'ls_geo_target_ibfk_2'; check that column/key exists
Can't DROP 'ls_geo_target_ibfk_3'; check that column/key exists
Can't DROP 'ls_invite_fk'; check that column/key exists
Can't DROP 'ls_invite_fk1'; check that column/key exists
Invalid default value for 'reminder_date_used'
Can't DROP 'ls_stream_event_ibfk_1'; check that column/key exists
Can't DROP 'ls_stream_subscribe_ibfk_1'; check that column/key exists
Can't DROP 'ls_stream_user_type_ibfk_1'; check that column/key exists
Can't DROP 'ls_talk_fk'; check that column/key exists
Can't DROP 'ls_talk_blacklist_fk_user'; check that column/key exists
Can't DROP 'ls_talk_blacklist_fk_target'; check that column/key exists
Can't DROP 'ls_talk_user_fk'; check that column/key exists
Can't DROP 'ls_talk_user_fk1'; check that column/key exists
Can't DROP 'ls_topic_fk'; check that column/key exists
Can't DROP 'ls_topic_fk1'; check that column/key exists
Can't DROP 'ls_topic_content_fk'; check that column/key exists
Can't DROP 'ls_topic_read_fk'; check that column/key exists
Can't DROP 'ls_topic_read_fk1'; check that column/key exists
Can't DROP 'ls_topic_tag_fk'; check that column/key exists
Can't DROP 'ls_topic_tag_fk1'; check that column/key exists
Can't DROP 'ls_topic_tag_fk2'; check that column/key exists
Can't DROP 'ls_userfeed_subscribe_ibfk_1'; check that column/key exists
Can't DROP 'ls_user_changemail_ibfk_1'; check that column/key exists
Can't DROP 'ls_user_field_value_ibfk_1'; check that column/key exists
Can't DROP 'ls_user_field_value_ibfk_2'; check that column/key exists
Can't DROP 'ls_user_note_ibfk_1'; check that column/key exists
Can't DROP 'ls_user_note_ibfk_2'; check that column/key exists
Can't DROP 'ls_topic_vote_fk1'; check that column/key exists
Can't DROP 'ls_wall_ibfk_1'; check that column/key exists
Can't DROP 'ls_wall_ibfk_2'; check that column/key exists

**Comment by venticello** [comment]
Судя по всему, тут не обновление, а установка поверх старой базы.
