### ISSUE TITLE
Ошибка при редактировании категорий

### ISSUE THREAD

**Issue by Acode7** [livestreet/livestreet#761]
При сохранении категории в админке добавляются символы справа и слева от описания категории. Сколько раз пересохранить - столько раз добавятся.

![screenshot_1](https://cloud.githubusercontent.com/assets/15953603/15602704/7d87257a-23ff-11e6-9cb0-70dd91374da2.png)

**Comment by venticello** [comment]
Описание категорий нигде кроме админки не выводится, поэтому использование тегов там ни к чему.

**Comment by venticello** [comment]
Тут фишка в том, что сейчас по-умолчанию для полей идет замена спец символов.
чтобы этого не было добавь в поле параметр:
`escape = false`
