### ISSUE TITLE
Компоненты для плагина

### ISSUE THREAD

**Issue by venticello** [livestreet/livestreet#765]
Как правильно прописать подключение компонента плагина, чтобы стили и скрипты описанные в component.json автоматически подключались?

**Comment by mzhelskiy** [comment]
Как и обычные компоненты, только с префиксом, например, для админки это 'admin:mycomponent'

**Comment by venticello** [comment]
Это то я понял прописываю имяплагина:компонент, как прописать, чтобы в общий конфиг не влезать ? сейчас через слияние массивов сделал, может есть более элегантное решение?

**Comment by mzhelskiy** [comment]
пока нету, можно еще в хуке через Component_Add()
