### ISSUE TITLE
Управление медиафайлами в админке

### ISSUE THREAD

**Issue by Kleindberg** [livestreet/livestreet#767]
Нечаянно завис сайт и одна и та же фотка загрузилась несколько раз. Предлагаю сделать для кнопки js-media-url-submit-upload в окне "Загрузка медиа-файлов" атрибут disabled во время загрузки файла на сервер (во избежание повторной отправки sumbit).

![image](https://cloud.githubusercontent.com/assets/6459395/17616399/25fa3972-607d-11e6-9733-5b4084410afb.png)

Также хотелось бы видеть в админке весь список ранее загруженных изображений (и файлов). Мало ли, понадобится удалить что-то не заходя на сервер.

**Comment by deniart** [comment]
Кнопку поправил, по поводу списка файлов лучше создать отдельный тикет в репо-ии админки.
