### ISSUE TITLE
Проблемы SEO

### ISSUE THREAD

**Issue by venticello** [livestreet/livestreet#772]
1. При отображении списка топиков у каждого заголовок h1, а h1 должен быть один на странице.
2. Для всех страниц (кроме топиков) по умолчанию указывается один и тот же description, что негативно влияет на позициях в поиске. Лучше его или не указывать или делать возможность для разделов задавать свой description.

**Comment by KarelWintersky** [comment]
>  а h1 должен быть один на странице.

Это конечно ужасающая проблема, кардинально влияющая на SEO! Куда же мы без SEO?! *сарказм*

**Comment by deniart** [comment]
Что бы прекратить споры по поводу заголовков, вынес их в конфиг шаблона. description можно менять с помощью плагинов

**Comment by venticello** [comment]
А не проще было проверять если список то h2 если не список то h1? Есть же переменная по которой можно определить.

**Comment by deniart** [comment]
Добавил опцию для списка
