### ISSUE TITLE
Совместимость с PHP7

### ISSUE THREAD

**Issue by axxxxx** [livestreet/livestreet#774]
Сборка не запускается на PHP 7

\framework\libs\vendor\DklabCache\Zend\Cache\Backend\File.php

функция get_magic_quotes_runtime удалена в php7

```
    private function _fileGetContents($file)
    {
        $result = false;
/*
        if (!is_file($file)) {
            return false;
        }
        if (function_exists('get_magic_quotes_runtime')) {
            $mqr = @get_magic_quotes_runtime();
            @set_magic_quotes_runtime(0);
        }
        $f = @fopen($file, 'rb');
        if ($f) {
            if ($this->_options['file_locking']) @flock($f, LOCK_SH);
            $result = stream_get_contents($f);
            if ($this->_options['file_locking']) @flock($f, LOCK_UN);
            @fclose($f);
        }
        if (function_exists('set_magic_quotes_runtime')) {
            @set_magic_quotes_runtime($mqr);
        }
*/
        return $result;
    }
```

/* комментируем лишнее для поднятия сайта */

Получаем следующие данные. Одна и та же страница с отключенным кешем на разных php
1) С чем связана особенность работы кеша в php7? (запросов в кеш больше чем в php5 при **отключенном(!!!)** кеше)
2) Нормально что php 7 генерирует запросов больше php 5 или виной тому закомментированный кусок кода выше?

php5
![php5](https://cloud.githubusercontent.com/assets/22236834/19387784/24238976-9225-11e6-8968-421a001cc6a5.png)
php7
![php7](https://cloud.githubusercontent.com/assets/22236834/19387783/2421e67a-9225-11e6-8654-11ec24534a01.png)

**Comment by mzhelskiy** [comment]
Этот кусок кода точно выдает ошибку и какую? Ведь там стоит условие с function_exists.

**Comment by venticello** [comment]
set_magic_quotes_runtime и get_magic_quotes_runtime можно полностью выпиливать из движка, т.к. с версии 5.4 магические кавычки полностью удалены из php и get_magic_quotes_runtime  всегда будет возвращать false. А у нас уже мин требование php 5.5

**Comment by axxxxx** [comment]
> Fatal error: Uncaught Error: Call to undefined function set_magic_quotes_runtime() in /home/site/web/site.com/public_html/framework/libs/vendor/DklabCache/Zend/Cache/Backend/File.php:665 Stack trace: #0 /home/site/web/site.com/public_html/framework/libs/vendor/DklabCache/Zend/Cache/Backend/File.php(376): Zend_Cache_Backend_File->_fileGetContents('/home/site...') #1 /home/site/web/site.com/public_html/framework/libs/vendor/DklabCache/Zend/Cache/Backend/File.php(309): Zend_Cache_Backend_File->_loadMetadatas('4aea4dc9f9d7dea...') #2 /home/site/web/site.com/public_html/framework/libs/vendor/DklabCache/Zend/Cache/Backend/File.php(640): Zend_Cache_Backend_File->_getMetadatas('4aea4dc9f9d7dea...') #3 /home/site/web/site.com/public_html/framework/libs/vendor/DklabCache/Zend/Cache/Backend/File.php(167): Zend_Cache_Backend_File->_test('4aea4dc9f9d7dea...', false) #4 /home/site/web/site.com/public_html/framework/libs/vendor/DklabCache/Cache/Backend/Profiler.php(34): Ze in /home/site/web/site.com/public_html/framework/libs/vendor/DklabCache/Zend/Cache/Backend/File.php on line 665

ошибка и при включенном и при выключенном кеше. комментирую кусок кода (первое сообщение), сайт работает.

**Comment by axxxxx** [comment]
PHP Warning:  Zend OPcache huge_code_pages: madvise(HUGEPAGE) failed: Invalid argument (22) in Unknown on line 0
PHP 7.0.12 (cli) (built: Oct 13 2016 16:56:51) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.12, Copyright (c) 1999-2016, by Zend Technologies

**Comment by axxxxx** [comment]
Не сразу заметил следующее. На старом php "мало" запросов, на новом php при закомментированном коде резко растет и количество запросов и обращений к кешу. Ниже скрин одной и той же страницы но на разных серверах (с разным php)

php5
![php5-1](https://cloud.githubusercontent.com/assets/22236834/19400628/ae506242-925f-11e6-8610-8fd91d9ecb42.png)
php7 (та же страница с закомментированным кодом)
![php7-1](https://cloud.githubusercontent.com/assets/22236834/19400629/ae566f98-925f-11e6-91ca-571bce0972c7.png)

**Comment by venticello** [comment]
На homestead php7 после выпилки magic_quotes_runtime нет ошибок, c memcached после его переустановки дружит.
У меня значительно меньше запросов, зря вы закоментировали весь файловый кэш, т.к. он используется ядром (даже если в настройках отключен), скорее всего из-за этого приходится несколько раз одни и те же данные выбирать.

**Comment by mzhelskiy** [comment]
fix https://github.com/livestreet/livestreet-framework/commit/cc1438697bd1f6726743fd19ada083806a34702e
