### ISSUE TITLE
Demo сайт для тестирования

### ISSUE THREAD

**Issue by lifecom** [livestreet/livestreet#776]
Предлагаю запустить демо (тестовую площадку) для 2.0.0, чтобы как можно больше пользователей могли протестировать, отписать сюда ишью... 
Не у каждого есть возможность у себя разворачивать...

**Comment by mzhelskiy** [comment]
Площадка уже есть, там копия текущего livestreet.ru на 2.0. Скоро анонсируем вместе с бетой 2.0.
