### ISSUE TITLE
Баг с комментариями

### ISSUE THREAD

**Issue by asphix** [livestreet/livestreet#778]
При отметке в админ-панели "Использовать или нет nested set при выборке комментов, увеличивает производительность при большом числе комментариев + позволяет делать постраничное разбиение комментов"

1) При добавлении ответа до перезагрузки страницы коммент появляется со смещением nested, 
2) после обновления страницы вообще перестаёт работать добавление комментариев, сворачивание/разворачивание дерева, форма добавления комментария развёрнута.

**Comment by asphix** [comment]
забыл уточнить. Шаблон developer. в synio вообще не работает отключение древовидности комментов (те они всегда древовидны, независимо от настройки)

**Comment by mzhelskiy** [comment]
Если подключить nested set на уже созданные ранее комменты, то их надо перестраивать. Добавил в админку опцию для перестроения дерева комментов. Проверил - работает нормально в обоих шаблонах.
