### ISSUE TITLE
Оптимизация медиа #1 тест превью

### ISSUE THREAD

**Issue by LStester** [livestreet/livestreet#780]
при добавлении превью
![screen shot 2016-11-06 at 19 12 06](https://cloud.githubusercontent.com/assets/23297238/20040017/35a9e6d2-a458-11e6-99eb-10e749b30347.JPG)
после добавления в топик ссылка битая, потому, что она ссылается не на файл превью для топика test/uploads/media/topic/2016/11/06/20/preview/54a27af7f33b45b1eb74_900x300crop.jpg

config из application:
```
$config['module']['media']['image']['preview']['sizes'] = array(  // список размеров, которые необходимо делать при создании превью
    array(
        'w'    => 900,
        'h'    => 300,
        'crop' => true,
    ),
    array(
        'w'    => 250,
        'h'    => 150,
        'crop' => true,
    ),
);
```

config из local:
```
$config['module']['media']['image']['preview']['sizes'] = array(  // список размеров, которые необходимо делать при создании превью
    array(
        'w'    => 400,
        'h'    => null,
        'crop' => true,
    ),
    array(
        'w'    => 800,
        'h'    => null,
        'crop' => true,
    ),
);
```

получается, что при создании превью он нарезает из local, а линк в топик подставляет из конфига application!

дальше
при создании превью вначале создаются куча ненужных файлов, а затем уже для превью создалось 2 файла, 
если заходим в редактирование топика видим 2 превью сразу - удаляем!
![screen shot 2016-11-06 at 19 20 44](https://cloud.githubusercontent.com/assets/23297238/20040019/45998520-a458-11e6-819b-d854c11eb696.JPG)
1. на фтп остаются файлы
2. нажимаем создать превью, выбираем ТОТ же загруженный файл и для него создаются еще два новых файла, а должны в моем понимании перезаписаться старые (даже если мы выберем другой файл для создания превью) ведь в превью мы можем использовать только 1 картинку верно же? Зачем плодить кучу мусора.

3. может форму превью от формы media сделать полностью независимыми? Так как из формы media можно удалять картинку, файлы превью при этом остаются на фтп, но сама превью из топика удаляется!
![screen shot 2016-11-06 at 20 06 33](https://cloud.githubusercontent.com/assets/23297238/20040280/d941098e-a45c-11e6-8c19-3cbeb0b59977.JPG)
![screen shot 2016-11-06 at 20 07 30](https://cloud.githubusercontent.com/assets/23297238/20040281/e0eb4ce4-a45c-11e6-8416-c9d8848bb30c.JPG)

**Узким местом лайвстрит всегда была графика и ее оптимизация, потому, что при более-менее посещаемом проекте с активными пользователями дисковое пространство улетает по 100мб в день легко, что совсем нерационально и раз уж в этой версии медиа был проработан для удобства загрузки графики, мое предложение максимально уделить внимание вопросу оптимизации**

я конечно понимаю, что при загрузке картинки создается по стандарту для нее куча файлов, а затем уже из нее делется превью, но это неоптимально совсем. Мое предложение по оптимизации:
1. разделить обе формы превью и топика, что я имею ввиду? Чтобы в модльном окне медиа для топика не было видно картинку для превью.
2. при загрузке только превью создавать файлы для конфига превью, а не для конфига стандартной загрузки графики
3.  конфиг можно вынести кол-во загрузаемых файлов в модальном окне. Превью на то она и превью, чтобы быть одной для топика, но если есть изращенцы, ради бога, могут поставить в конфиге 30 и будет 30 превьющек из которых он все-рано выберет только одну.

P.S. готовлю еще кучу сюрпризов по media
с уважением

**Comment by deniart** [comment]
Локальный конфиг видимо некорректный, т.к. выдает деление на ноль в ответе, @mzhelskiy проверь.
Механизм выбора превью изменять пока не планируем.

**Comment by agran** [comment]
У меня так же подвисло при добавлении превью для топика. Потом выбрал фото поменьши и тогда загрузилось нормально.

**Comment by mzhelskiy** [comment]
Конфиг составлен неверно, если установлено 'crop' => true, то h и w необходимо обязательно указать.
Проверил - добавил превью из нового файла, создались стандартные копии + копии для превью. Удалил превью - копии для превью удалились. Второй кейс - удалил оригинальное фото, превью на его основе тоже удалилось со всеми файлами.

**Comment by LStester** [comment]
прошло 6 лет, удачного развития!

**Comment by Xmk** [comment]
Раз о media, то такой вопрос.
Почему тайтл для изображения привязывается к объекту media а не media target? Я допустим хочу использовать ранее загруженное изображение, но с другим описанием.
