### ISSUE TITLE
Поле получатель не заполняется

### ISSUE THREAD

**Issue by agran** [livestreet/livestreet#787]
Через панель управления если в списке пользователей выбрать в меню пункт Сообщение, то поле получатель не заполняется
![22222](https://cloud.githubusercontent.com/assets/7409036/21262501/ab586138-c3a2-11e6-98a1-0c189268f46a.png)
![222223](https://cloud.githubusercontent.com/assets/7409036/21262502/ab5b7a26-c3a2-11e6-9b71-10013f3d8be8.png)

**Comment by deniart** [comment]
Исправлено https://github.com/livestreet/lsplugin-admin/commit/45f5a1c568c12df691ea1a125575911a32583e3a
