### ISSUE TITLE
Аватарки пользователей

### ISSUE THREAD

**Issue by kseniya93** [livestreet/livestreet#790]
Добавьте аватарки пользователей в блок активность, как в блоке блоги. Таких же размеров.

**Comment by kseniya93** [comment]
Очень нужны аватарки в блоке активность.

**Comment by mzhelskiy** [comment]
это зависит от шаблона, в synio их нет

**Comment by kseniya93** [comment]
Понимаю, но хотелось бы, чтобы они появились. С ними было бы намного удобнее следить за блоком. Аватарок в блоке блоги, тоже не было, но их добавили.
