### ISSUE TITLE
[LS 2] Кэш + PHP 7 = крэш

### ISSUE THREAD

**Issue by Oreolek** [livestreet/livestreet#803]
Dklabcache использует функцию `set_magic_quotes_runtime`, которую [убрали в PHP7.](https://secure.php.net/manual/en/function.set-magic-quotes-runtime.php) При попытке включить кэш LiveStreet 2 падает и обратно уже сама не поднимется.

Файл `/framework/libs/vendor/DklabCache/Zend/Cache/Backend/File.php`:664

**Comment by Xmk** [comment]
https://github.com/jeka-kiselyov/dklabcache/commit/9998c109743711b8a6f9b5130e7fe210c588a9d4

**Comment by mzhelskiy** [comment]
В LS2 есть проверка на существование функции set_magic_quotes_runtime.
Была не последняя версия фреймворка?
