### ISSUE TITLE
Анимация при сохранении топика

### ISSUE THREAD

**Issue by Oreolek** [livestreet/livestreet#804]
Обычная анимация AJAX запроса в LiveStreet 2 почти не видна: ну что-то там сверху промелькнуло и всё.

Но при сохранении топика это становится серьёзной проблемой, потому что пользователь может её не заметить и думает, что ничего не произошло. А потом постит одно и то же по несколько раз.

**Comment by Xmk** [comment]
Разве после анимации нет всплывающего уведомления о том, что топик успешно опубликован и редиректа на страницу созданного топика?

**Comment by Oreolek** [comment]
Дык пока сохранение пройдёт и анимация закончится, человек может ещё пару раз с нетерпения нажать.

**Comment by Xmk** [comment]
боюсь у него это не получится - форма полностью блокируется (кнопки в том числе), а если даже как-то умудрится в момент между ответом от сервера и редиректом - увидит ошибку о том, что он уже публиковал топик с таким содержанием
