### ISSUE TITLE
Стена

### ISSUE THREAD

**Issue by Xmk** [livestreet/livestreet#813]
Предлагаю создать для записей на стене отдельный файл, а не использовать шаблон компонента comment. (или как вариант добавить переменную, как примесь к названию хуков, а также использовать mods)
Это позволит более гибко стилизовать элементы в кастомных шаблонах и исключит вывод кнопки "полное удаление" выводимой админкой для комментов (если ее нажать будет удален коммент по id коммента стены): https://yadi.sk/i/ZMG12OMu3B3m7m

**Comment by deniart** [comment]
Запись для стены сейчас в отдельном файле (wall/wall.entry.tpl), в своем скине там что угодно можно прописать

**Comment by Xmk** [comment]
стилизация стилизацией, а ошибка вывода кнопки админкой по хуку для комментариев это другое.

**Comment by mzhelskiy** [comment]
@deniart трабл в том, что хуки в итоге получаются одинаковые для комментов и стены

**Comment by deniart** [comment]
https://github.com/livestreet/livestreet/commit/e598a146087e0d8e8ec3cb2b7033b0546f633878
