### ISSUE TITLE
Валидация дня рождения

### ISSUE THREAD

**Issue by Xmk** [livestreet/livestreet#815]
Предлагаю добавить валидацию дня рождения в настройках профиля.
Через валидатор Date, и проверять на дату в будущем и в слишком далеком прошлом (-100 лет например, хотя самому старому человек на земле 122 года).
https://yadi.sk/i/BiseEt_13B4SW4

P.S. Предлагаю юзера прогонять через валидатор и убрать проверки из экшна settings

**Comment by mzhelskiy** [comment]
С использованием валидатора из сущности текущего юзера есть ряд проблем, в которыми пока не хочется заморачиваться. Там пока не заюзать _setDataSafe() + если для валидации изменять значения полей текущего юзера, то эти поле могут быть сохранены даже после неудачной валидации (например, какой-то плагин обновит в хуке объект текущего юзера)

**Comment by Xmk** [comment]
Понял, может хотя бы сюда: https://github.com/livestreet/livestreet/blob/master/application/classes/actions/ActionSettings.class.php#L577
отсюда проверку вставить? https://github.com/livestreet/lsplugin-admin/blob/master/classes/actions/admin/EventUsers.class.php#L338

**Comment by mzhelskiy** [comment]
fix https://github.com/livestreet/livestreet/commit/23f143822d6d1355ff554090fb08b181e6f26aa2
