### ISSUE TITLE
Иконки для кастомных типов контента

### ISSUE THREAD

**Issue by Xmk** [livestreet/livestreet#816]
Предлагаю добавить в форму создания\редактирования типа "топика" (переименовать в контент надо кстати бы...)
поле имени иконки (или загрузки файла изображения), лучше имя иконки (из FA)
Использовать, например вот тут:
https://yadi.sk/i/lmDOQQUV3B4ZR8
(хоть из developer и убрали эту модалку, в выпадающем меню они смотреться будут не хуже - https://yadi.sk/i/0pdbbwPG3B4dZ8)
ну и картинки блога\лс и др. соответственно заменить на иконки, смотрится даже лучше - https://yadi.sk/i/oZw2ZGD53B4htP)

**Comment by mzhelskiy** [comment]
@deniart добавил вывод иконки (настраивается в админке) в попапа создания контента, надо оформить

**Comment by deniart** [comment]
https://github.com/livestreet/livestreet/commit/3b0c7cdf8a72d38a96122c7d2439151b29aecf43
