### ISSUE TITLE
Вынести "Рейтинг" в языковые файлы

### ISSUE THREAD

**Issue by kcop4uk** [livestreet/livestreet#821]
application\frontend\components\user\header.tpl
application\frontend\skin\synio\components\user\header.tpl

Вынести слово "Рейтинг" в языковые файлы

**Comment by mzhelskiy** [comment]
Не понял, где там вынести. Уже используется {lang 'vote.rating'}

**Comment by kcop4uk** [comment]
Ух ты, файл уже месяц как исправлен, а я неделю назад архивчик с сайта подтянул, думал свежий.
*виноват, я всегда буду pull'ить последние апдейты с гита, перед тем как писать баг-репорт :)*

закрыто
