### ISSUE TITLE
Формы выбора дергаются в процессе обновления страницы

### ISSUE THREAD

**Issue by kseniya93** [livestreet/livestreet#829]
Список:

Форма выбора собеседников для отправки сообщений.
Форма выбора пользователей для добавления в черный список.
Форма выбора пользователей для поиска по ленте и по активности.
Форма выбора блога при создании топика.

Примеры:

http://livestreet.ru/uploads/images/01/99/20/2017/02/05/324d35.jpg
http://livestreet.ru/uploads/images/01/99/20/2017/02/05/289ff5.jpg

На версии 1.0.3 такого не было.

**Comment by kseniya93** [comment]
Исправили?

**Comment by mzhelskiy** [comment]
fix
