### ISSUE TITLE
Фотосет разворачивается вертикально

### ISSUE THREAD

**Issue by kseniya93** [livestreet/livestreet#831]
Фотосет в ленте и при открытии в процессе обновления разворачивается вертикально. Такого быть не должно.

Примеры:

http://livestreet.ru/uploads/images/01/99/20/2017/02/09/6e8fed.jpg
http://livestreet.ru/uploads/images/01/99/20/2017/02/09/9735f3.jpg

**Comment by Xmk** [comment]
Это очень даже логично.
Если у тебя в браузере отключен JS, то как-то же должно отображаться?

**Comment by kseniya93** [comment]
С точки зрения принципа работы и отображения фотосет сильно отличается от слайдера? Просто на слайдерах подобного нет. Обновляешь страницу, ничего не съезжает и не дергает.

**Comment by Xmk** [comment]
по сути, этот то же слайдер. только с корректным отображением при выключенном js

**Comment by kseniya93** [comment]
Нужно с этим что-то делать. Когда загружается любая страница с фотосетом особенно из большого количества снимков все это дело разворачивается вертикально на огромную длину и выглядит, как раздражающая неисправность. Нужно, чтобы было, как со слайдерами, где снимки не разворачиваются и не съезжают при обновлении или загрузки страницы.

**Comment by mzhelskiy** [comment]
fix
