### ISSUE TITLE
Редактор TinyMCE не парсит заголовки типа h2, h3

### ISSUE THREAD

**Issue by vinznsk** [livestreet/livestreet#836]
Создаю заголовки в редакторе h2, h3, они отображаются корректно.

После сохранения топика заголовки в тексте не выделены, в коде отображаются как обычный текст
![2017-02-15_20-39-58](https://cloud.githubusercontent.com/assets/702948/22977942/4498b3f2-f3c3-11e6-84f1-fb564602d561.jpg)

**Comment by mzhelskiy** [comment]
При необходимости можно добавить в конфиг config/jevix.php поддержку тегов h2/h3
