### ISSUE TITLE
Иконки не отображаются

### ISSUE THREAD

**Issue by kseniya93** [livestreet/livestreet#839]
Иконки на кнопках редактировать и удалить и при выборе создания типов публикаций и возможно, где-то еще на демке не отображаются. Вместо них отображаются квадраты. Исправьте.

**Comment by kseniya93** [comment]
На опере не отображаются.

**Comment by mzhelskiy** [comment]
проверил в Опере - работает

**Comment by kseniya93** [comment]
Уже отображаются.
