### ISSUE TITLE
Листание фотосета

### ISSUE THREAD

**Issue by kseniya93** [livestreet/livestreet#844]
Сделать так, чтобы фотосет можно было листать стрелочками на клавиатуре. Очень неудобно листать мышкой.

**Comment by mzhelskiy** [comment]
В assets.init.js шаблона можно добавить опцию для слайдера:

`
$( '.fotorama' ).livequery(function() {
        $( this ).lsSlider({ keyboard: true });
    });
`
Но будет работать только для первого фотосета на странице.
