### ISSUE TITLE
Переезд с 1.0.3 - папки в uploads

### ISSUE THREAD

**Issue by lifecom** [livestreet/livestreet#845]
При обновлении с 1.0.3 нужен скрипт, меняющий название папок
Вот папка с аватарами с 1.0.3 - /uploads/images/00/00/01/YYYY/MM/DD/
Вот папка с аватарами с 2.0.0 - /uploads/images/users/000/000/001/YYYY/MM/DD/

**Comment by mzhelskiy** [comment]
Побочный эффект обновления
