### ISSUE TITLE
Не отображается iframe

### ISSUE THREAD

**Issue by vinznsk** [livestreet/livestreet#848]
При вставке iframe в текст статьи, ничего не отображается

`<iframe src="https://www.google.com/maps/d/u/0/embed?mid=1pxyfPopqdtJ7Msuzw7_2xXhXM9w" width="640" height="480"></iframe>`

**Comment by mzhelskiy** [comment]
в настройках парсера config/jevix.php нужно разрешить домен google.com для iframe
