### ISSUE TITLE
Инсталятор

### ISSUE THREAD

**Issue by Xmk** [livestreet/livestreet#857]
При условии того, что сейчас [тут](https://github.com/livestreet/livestreet/blob/master/application/install/bootstrap.php#L4) выставлена версия 2.0.1
не возможно обновиться с 1.0.3 (нет такого конвертера - 1_0_3_to_2_0_1)
Нужно как-то усовершенствовать инсталлер.

В процессе конверта было бы хорошо блокировать кнопки и выводить колесо какое нибудь.

ЗЫ: я конвертер 0.5.2 to 1.0.3 к нему адаптировал (обновлял сайт с 0.5 до 2) - запулить? пригодится может кому нибудь.

**Comment by mzhelskiy** [comment]
> я конвертер 0.5.2 to 1.0.3 к нему адаптировал (обновлял сайт с 0.5 до 2) - запулить?

не, не надо, а то потенциальными проблемами еще больше завалят

**Comment by Xmk** [comment]
еще заметил в инсталлере ошибку с выводом ошибок.
попозже залью пулл, распишу что к чему.
можно их конечно не трогать, но лучше путь будет. дебажить проще
