### ISSUE TITLE
Pages

### ISSUE THREAD

**Issue by Xmk** [livestreet/livestreet#863]
http://livestreet.ru/blog/addons/18828.html#comment298374
напомнили о давнишней неувязке пагинации LS.

Можно что-то придумать?

**Comment by mzhelskiy** [comment]
А что криминального в этом? В урле можно руками что только не написать.
https://habrahabr.ru/hub/livestreet/page100/

**Comment by Xmk** [comment]
нет ничего криминального.
на хабре не замечал, но в основном на сайтах привык что вот-так https://www.adme.ru/tvorchestvo-hudozhniki/page651/

мне впрочем не мешает)
