### ISSUE TITLE
Добавить - Генерировать Привью к топикам в админку

### ISSUE THREAD

**Issue by Lepraz** [livestreet/livestreet#870]
Нет кнопки генерировать привью топиков в админке!

**Comment by mzhelskiy** [comment]
Добавили опцию перегенерации превью в админку (нужно обновить двиг)

**Comment by Lepraz** [comment]
Обновил двиг, вобще всё рухнуло и ничего не работает :-(((




d0z0z0d

От: Maxim Mzhelskiy
Отправлено: 2017-04-16 06:36
Кому: livestreet/livestreet
Копия: Lepraz; Author
Тема: Re: [livestreet/livestreet] Добавить - Генерировать Привью к топикам в админку (#870)
Добавили опцию перегенерации превью в админку (нужно обновить двиг)

**Comment by mzhelskiy** [comment]
Нужно больше конкретики.
Обновлять нужно через инсталлятор, т.к. там патчится БД.

**Comment by Lepraz** [comment]
В процессе выдает ошибку - Table 'ЖЖЖ.prefix_topic_photo' doesn't exist 
и дальше не идет, т.е. обновление не проходит

**Comment by mzhelskiy** [comment]
При обновлении нужно выбрать правильную текущую версию LS, если стояла 2.0.0, то и выбирать нужно ее на шаге обновления.

**Comment by Lepraz** [comment]
![2017-04-19_10-40](https://cloud.githubusercontent.com/assets/24349900/25169169/b526cc1a-24ee-11e7-9662-9638d80e1362.jpg) Выбираю правильную, но не обновляет оно.

**Comment by mzhelskiy** [comment]
исправил - https://github.com/livestreet/livestreet/commit/9bf001dac83031e85c8bd137b56b5933ac1e0520

**Comment by Lepraz** [comment]
Обновление прошло успешно, но сайт после него не поднимается - isra.club
![2017-04-19_11-59](https://cloud.githubusercontent.com/assets/24349900/25171882/f563e62e-24f7-11e7-8f3f-1574a2522083.jpg)

**Comment by mzhelskiy** [comment]
Нужно смотреть логи в корне сайта /application/logs и логи вебсервера. Предварительно почистив каталог /application/tmp

**Comment by Lepraz** [comment]
на время установки обновления 11 раз пишет:
Uncaught Exception RuntimeException: "Class "ModuleSitemap" not found!" at /home4

**Comment by mzhelskiy** [comment]
Значит двиг обновлен без обновления фреймворка - каталог /framework

**Comment by Lepraz** [comment]
Да, глянул архив скачанный с гитхаба - этот каталог пуст.

**Comment by mzhelskiy** [comment]
проблема решилась?

**Comment by Lepraz** [comment]
Сорри, я не програмист, и не совсем понимаю что нужно делать, и как решать эту проблему.

**Comment by mzhelskiy** [comment]
Скачать от сюда https://github.com/livestreet/livestreet-framework  обновленный фреймворк и положить его в тот каталог

**Comment by Lepraz** [comment]
Сайт заработал, но не пойму где смотреть изменения, где генерация привью и встроенный сайтмап находятся?

**Comment by mzhelskiy** [comment]
/sitemap.xml

Перегенерация превью в админке Утилиты -> Оптимизация (для этого нужно еще и админку обновить с github)

**Comment by Lepraz** [comment]
Админка ведь плагин, по идее должно писать что есть обновление? Обновил, появилась генерация привью, сайтмап тот что был модулем перестал работать, после его отключения заработал встроенный.

**Comment by Lepraz** [comment]
Ещё такой вопрос, в процессе установки обновления вся инфа - т.е. имя БД, юзер БД, пасс-БД, видны любому кто открыл URL?! Мне как бы все-равно, но для ресурсов с высокой посещаемостью, помоему логичнее чтобы админ вводил все эти данные, т.е. чтобы все эти поля были пустыми.

**Comment by Lepraz** [comment]
Кнопка Перегенерировать все превью появилась, после клика выдает Перегенерация завершена, но привью не появляются

**Comment by mzhelskiy** [comment]
Это функционал перегенерации уже **существующих** превью к новым размерам.

**Comment by Lepraz** [comment]
Обновил шаблон, привьюшки в similar topics отвалились, новые через админку не генерируются

**Comment by Xmk** [comment]
@Lepraz это возможно косяк моего плагина, проверю. Дай ссылку на сайт

**Comment by Lepraz** [comment]
http://isra.club/2017/03/14/a-k-vosmi-godam-ya-botal-na-ivrite-i-byl-sionistom-v-nature.html

**Comment by Xmk** [comment]
я так понимаю, что у автора шаблона кастомный вывод моего блока - и там задается вывод превью - там где то указывается размер превью.
скорей всего вы изменили размер в конфиге, а в шаблоне он прописан жестко.

p.s. сегодня\завтра выйдет новая версия плагина с опциональной возможностью отображения с превью

**Comment by kseniya93** [comment]
LS 2.0.1 уже готова? Когда выйдет релиз?
