### ISSUE TITLE
Перевести фразы на английский язык

### ISSUE THREAD

**Issue by vinznsk** [livestreet/livestreet#872]
При установке английской версии, некоторые фразы остаются непереведенными. 
Примеры на скриншотах во вложении
![2017-04-12_16-34-54](https://cloud.githubusercontent.com/assets/702948/24951318/2c2079ca-1f9e-11e7-8a86-3ee28a49f068.jpg)
![2017-04-12_16-35-31](https://cloud.githubusercontent.com/assets/702948/24951319/2c21cc94-1f9e-11e7-8bce-3f3f82f1fb90.jpg)
![2017-04-12_16-35-55](https://cloud.githubusercontent.com/assets/702948/24951320/2c223c2e-1f9e-11e7-8d2c-f06f7dc118df.jpg)

**Comment by mzhelskiy** [comment]
Это текстовки фреймворка, они уже переведены
