### ISSUE TITLE
Размер шрифта кнопок

### ISSUE THREAD

**Issue by kseniya93** [livestreet/livestreet#876]
Уже писалось, но повторю, ибо исправлено не было. Размер шрифта кнопок Войти и Регистрация меньше размера шрифта Топики Блоги Пользователи и Активность. Исправьте.

**Comment by mzhelskiy** [comment]
Это специфика конкретного шаблона. Всем с ним не угодить.

**Comment by kseniya93** [comment]
Это не специфика. Это баг. Нигде такого нет. Так можно все на специфику списывать.

**Comment by kseniya93** [comment]
Почему в шаблон вносились изменения по сравнению с версией LS 1.0.3? Почему не вносилось и отказ вносить изменения не списался на специфику?

**Comment by Xmk** [comment]
🤐
