### ISSUE TITLE
Перерисовка фото в LS

### ISSUE THREAD

**Issue by Volodya1234** [livestreet/livestreet#881]
Проблема с том что после загрузке картинки на 500КБ, движок ее перерисовывает на 3МБ и больше, касается также превью. Причем оригинал если в .png, то он также растет в размере.

Замечено только в PNG.

**Comment by mzhelskiy** [comment]
Если поменять драйвер с gd на imagick?

**Comment by Volodya1234** [comment]
imagick также рейсайзит на нескольких фото добавляет безбашенный размер. 

На текущий момент поставил, при таких настройках не жрет размер:
```
$config['module']['image']['driver'] = 'gd';
$config['module']['image']['params']['default']['size_max_width'] = 15000;
$config['module']['image']['params']['default']['size_max_height'] = 15000;
$config['module']['image']['params']['default']['format_auto'] = false;
$config['module']['image']['params']['default']['format'] = 'jpg';
$config['module']['image']['params']['default']['quality'] = 100;
```
Но качество фото такое себе, jpg сразу видно.

Допустим есть фото: https://i.13.wf/2017/07/18/1500355559-8367.jpg

И настройка фото в png на gd:
```
$config['module']['image']['driver'] = 'gd';
$config['module']['image']['params']['default']['size_max_width'] = 15000;
$config['module']['image']['params']['default']['size_max_height'] = 15000;
$config['module']['image']['params']['default']['format_auto'] = false;
$config['module']['image']['params']['default']['format'] = 'png';
$config['module']['image']['params']['default']['quality'] = 100;
```
И оно будет занимать в 30 раз больше: https://i.13.wf/2017/07/18/1500355563-4944.png

При такой настройке оно будет занимать оригинал как надо(проверил в Paint.Net при создании jpg -> png, такой же размер выдает) в png:
```
$config['module']['image']['driver'] = 'imagick';
$config['module']['image']['params']['default']['size_max_width'] = 15000;
$config['module']['image']['params']['default']['size_max_height'] = 15000;
$config['module']['image']['params']['default']['format_auto'] = false;
$config['module']['image']['params']['default']['format'] = 'png';
$config['module']['image']['params']['default']['quality'] = 100;
```
Вот размер: https://i.13.yt/2017/07/18/1500355561-7438.png

**Comment by mzhelskiy** [comment]
при format_auto = false ставить format = png не нужно, конечно он все jpg будет перегонять в png и размер в разу увеличится

**Comment by Volodya1234** [comment]
При таком:
```
$config['module']['image']['driver'] = 'imagick';
$config['module']['image']['params']['default']['size_max_width'] = 15000;
$config['module']['image']['params']['default']['size_max_height'] = 15000;
$config['module']['image']['params']['default']['format_auto'] = false;
$config['module']['image']['params']['default']['quality'] = 100;
```
Столько: https://i.13.yt/2017/07/18/1500357700-6383.png

При таком:
```
$config['module']['image']['driver'] = 'gd';
$config['module']['image']['params']['default']['size_max_width'] = 15000;
$config['module']['image']['params']['default']['size_max_height'] = 15000;
$config['module']['image']['params']['default']['format_auto'] = false;
$config['module']['image']['params']['default']['quality'] = 100;
```
Столько: https://i.13.yt/2017/07/18/1500357702-074.png

Фото занимает 235КБ примерно, Оно сохраняет оригинал в 1МБ в том же формате и объем растет в 4 раза 1000/250 грубо говоря.

**Comment by Volodya1234** [comment]
То будет практически как оригинал размер. Поставил вот так:

```
$config['module']['image']['driver'] = 'imagick';
$config['module']['image']['params']['default']['size_max_width'] = 15000;
$config['module']['image']['params']['default']['size_max_height'] = 15000;
$config['module']['image']['params']['default']['format_auto'] = false;
$config['module']['image']['params']['default']['quality'] = 99;
```

**Comment by mzhelskiy** [comment]
Значит проблема решилась?

**Comment by Volodya1234** [comment]
По сути да. thx;

**Comment by Volodya1234** [comment]
Есть одна вещь.

Все картинки теперь по умолчанию в jpg делаются, хотя формат принудительный - убран
формат авто - false
А если включить формат авто - true, снова начинается увеличение.

**Comment by mzhelskiy** [comment]
Для эксперимента выставил на демо сжатие на 91%, теперь не сильно увеличивает.
