### ISSUE TITLE
Сделать поиск по сайту livestreet.ru

### ISSUE THREAD

**Issue by 1F6B6** [livestreet/livestreet#896]
Поиск по сайту не работает уже несколько месяцев. Пользователи многократно сообщали об этом [Не работает поиск и мобильная версия](http://livestreet.ru/blog/questions/19004.html), [Поиск по сайту livestreet.ru](http://livestreet.ru/blog/19019.html), [Не работает поиск на этом сайте](http://livestreet.ru/blog/bugreport/19001.html).

**Comment by mzhelskiy** [comment]
fix
