### ISSUE TITLE
Добавить модераторов на сайт livestreet.ru

### ISSUE THREAD

**Issue by 1F6B6** [livestreet/livestreet#901]
На сайте творится полная анархия. Никто не удаляет спам, вопросы которые уже задавались множество раз, глупые комментарии. Предлагаю назначить модераторами активных участников сообщества. Например [vOFFka](http://livestreet.ru/profile/vOFFka/), [yuran](http://livestreet.ru/profile/yuran/), [lifecom](http://livestreet.ru/profile/lifecom/) и любых других участников которые могли бы поддерживать порядок.

**Comment by mzhelskiy** [comment]
удалил спам
модераторы назначаются только в рамках конкретного блога

**Comment by 1F6B6** [comment]
@mzhelskiy это не решает проблемы. что делать с подобным мусором http://livestreet.ru/blog/18723.html, http://livestreet.ru/blog/18714.html, http://livestreet.ru/blog/18712.html? и таких топиков и комментариев десятки, если не сотни.

**Comment by 1F6B6** [comment]
@mzhelskiy куда можно дальше репортить о таких страницах для их удаления?

**Comment by mzhelskiy** [comment]
можно на office@livestreetcms.com
