### ISSUE TITLE
Не работает генерация привью к топикам.

### ISSUE THREAD

**Issue by Lepraz** [livestreet/livestreet#904]
С последним обновлением LS2 в админке появилась генерация привью к топикам, у всех корректно работает? Кто нить проверял эту фичу? У меня не срабатывает ((

**Comment by mzhelskiy** [comment]
Что именно не срабатывает? Там функционал перегенерации, а не генерации превью (например, по изображениям в посте). Для успешной перегенерации должны быть сохранены оригиналы изображения для превью (можно отключить в конфиге).

**Comment by Lepraz** [comment]
Не перегенирирует, пока в ручную не сгенерируешь не появляются в похожих новостях - http://isra.club/2017/03/31/agit-plakaty-evreyskih-sionistov-pervoy-volny.html

**Comment by Lepraz** [comment]
В старой версии делало картинку привью из видео, настраивалось в конфиге.  В LS2 по умолчанию не делает, а где включить эту опцию не нахожу.

**Comment by mzhelskiy** [comment]
Проверил - успешно создались новые размеры превью.
Суть работы - если в конфиге задать новые размеры превью, то в админке можно запустить генерацию изображений с этими размерами.
Генерация завершается успешно? Физически на сервере файлы с новыми размерами появляются? Новые размеры точно корректно прописаны в конфиге?

> В старой версии делало картинку привью из видео, настраивалось в конфиге. В LS2 по умолчанию не делает, а где включить эту опцию не нахожу.

Это делалось плагинов, в новой версии такого функционала нет.

**Comment by Lepraz** [comment]
Наверное дело в шаблоне и модуле Similar Topics.

Другой вопрос, касается rel="nofollow"> и noindex который можно включить в конфиге для сторонних URL, в каком файле находится сам этот добавлеемый в урлы текст? Хочу добавить в него target="_blank", чтобы добавляло сразу как target="_blank" rel="nofollow">

**Comment by mzhelskiy** [comment]
nofollow делается здесь https://github.com/livestreet/livestreet-framework/blob/6ee95bbb0c11b50271755a460592a80c3dd88680/classes/modules/text/Text.class.php#L106
Но для добавления target="_blank" достаточно изменить конфиг jevix.php - добавить дефолтный обязательный атрибут для a.

**Comment by Lepraz** [comment]
Я извиняюсь, но я не програмист, добавить дефолтный атрибут для а - сорри что не знаю как)))
Пробовал изменить строку 105 в файле
framework/classes/modules/text/Text.class.php
у меня она вот так выглядит


$this->oJevix->cfgSetTagParamDefault('a', 'rel', 'nofollow', true); 

поменял на то что у вас в 106, сбросил кэш движка, но ниче не поменялось

**Comment by mzhelskiy** [comment]
Добавляется здесь - https://github.com/livestreet/livestreet/blob/2.0.1/application/config/jevix.php#L34  там, кстати, он уже добавлен.
Чтобы изменения приняли силу нужно текст топика пересохранить, т.к. парсинг происходит в момент сохранения постов.

**Comment by Lepraz** [comment]
Спасибо, все работает

**Comment by Lepraz** [comment]
А как купить Плагин «AutoOpenId» из каталога?

**Comment by mzhelskiy** [comment]
> А как купить Плагин «AutoOpenId» из каталога?
написать на rus.engine@gmail.com
