### ISSUE TITLE
при указании url топика выдает, после не находит топик

### ISSUE THREAD

**Issue by devM4x** [livestreet/livestreet#919]
добрый день, в чем проблема?

 я установил ls  и когда создаю топик и он мена перекидывает как я понимаю на сам топик и nginx мне выдает что такого файла не существует. 

что не не так я сделал? 

как пример https://soundforestfm.info/2018/10/27/interesnoe-video.html

Так же не понятно как довать рейтинги пользователям, у меня создан тестовый пользователь и у него два топика, я к примеру проголосовал за них  и он уже может создавать блоги. как то не логично. и как вообще сделать так, чтобы пользователь который только зарегестрировался. мог только коментировать, а потом когда уже карма появляется мог и топики создавать, а затем уже и блоги когда карма будет соотвествующая  не понятно

**Comment by mzhelskiy** [comment]
Возможно в nginx есть настройка, которая перехватывает урлы с расширением ".html", ее нужно убрать.
По рейтингам - в основном конфиге можно настроить разные ограничения по рейтингам для разных действий.

**Comment by olezhikz** [comment]
Покажите свой конфиг nginx

**Comment by devM4x** [comment]
Лови, только я в этом nginx'e черт ногу сломит

`server {
        listen 80;
        server_name  myexamplehost.info www.myexamplehost.info;
        rewrite ^ https://$http_host$request_uri? permanent;    # force redirect http to https
        server_tokens off;
}

server {
        listen 443 ssl;
        listen [::]:443 ipv6only=on ssl;
        # ssl on;
        ssl_certificate /etc/letsencrypt/live/myexamplehost.info/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/myexamplehost.info/privkey.pem;
        server_name myexamplehost.info;
        ssl_session_cache shared:SSL:5m;
        ssl_session_timeout 5m;

        ssl_dhparam /etc/nginx/dhparam.pem;

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers on;

        ssl_ciphers "923sdfuy

        if ($scheme != "https") {
             return 301 https://$host$request_uri;
        }

        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";
        server_tokens off;
        client_max_body_size 10m;

        access_log /var/log/nginx/myexamplehost.info.access_log;
        error_log /var/log/nginx/myexamplehost.info.error_log;

        root /var/www/myexamplehost.info/public_html;
        index index.php;

        location / {
                try_files $uri $uri/ /index.php?q=$uri&$args;
        }

        location /phpmyadmin {
                auth_basic "Secure page";
                auth_basic_user_file /etc/nginx/pma_pass;
        }

        location ~ \.php {
                fastcgi_pass  unix:/var/run/php/php7.2-fpm.sock;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;
        }

        location ~ \.(tpl|xml|log)$ {
                deny all;
        }

        # static file 404's aren't logged and expires header is set to maximum age
        location ~* \.(jpg|jpeg|gif|css|png|js|ico|html)$ {
                access_log off;
                expires max;
        }

        location ~ /\.ht {
                deny  all;
        }
}
`
